import dataclasses
import re
import tempfile

import numpy as np
import pytest
import torch
import xarray as xr

from fme.ace.inference.evaluator import main as inference_evaluator_main
from fme.ace.testing import DimSizes
from fme.ace.testing.fv3gfs_data import get_nd_dataset
from fme.ace.train.train import main as train_main
from fme.core.coordinates import LatLonCoordinates
from fme.core.testing.wandb import mock_wandb


def save_ice_nd_netcdf(
    filename: str,
    dim_sizes: DimSizes,
    variable_names: list[str],
    timestep_days: float = 1.0,
):
    """
    Saves a netCDF file with synthetic ice data, including masks and NaNs.
    Inspired by fme/coupled/data_loading/test_data_loader.py::_save_netcdf
    and fme.ace.testing.fv3gfs_data.save_nd_netcdf.
    """
    base_variable_names = [
        name for name in variable_names if not name.startswith("mask_")
    ]

    # Use a modified DimSizes for base dataset to avoid issues with nz_interface
    # if get_nd_dataset interprets it in a way not suitable for ice vars
    base_dim_sizes = dataclasses.replace(dim_sizes, nz_interface=1)

    ds = get_nd_dataset(
        dim_sizes=base_dim_sizes,
        variable_names=base_variable_names,
        timestep_days=timestep_days,
        include_vertical_coordinate=False,  # No ak/bk for ice
    )

    rng = np.random.default_rng(0)  # For reproducibility

    horizontal_dims = list(map(lambda x: x.name, dim_sizes.horizontal))
    horizontal_shape = list(map(lambda x: x.size, dim_sizes.horizontal))
    horizontal_coords = {dim: ds.coords[dim] for dim in horizontal_dims}

    if "mask_2d" in variable_names:
        mask_data_values = np.ones(horizontal_shape, dtype=np.float32)
        mask_data_values[1, 1] = 0.0  # small island
        ds["mask_2d"] = xr.DataArray(
            mask_data_values.astype(np.float32),
            dims=horizontal_dims,
            coords=horizontal_coords,
        )

    for var_name in base_variable_names:
        if var_name not in ds:  # Skip if not generated by get_nd_dataset
            continue
        if "mask_2d" in variable_names:
            ds[var_name] = ds[var_name].where(ds["mask_2d"] == 1, float("nan"))

    if "siconc" in ds:
        sea_ice_ocean = xr.DataArray(
            rng.uniform(0.0, 0.2, size=ds["siconc"].shape),
            dims=ds["siconc"].dims,
            coords=ds["siconc"].coords,
        )
        if "mask_2d" in ds:
            sea_ice_ocean = sea_ice_ocean.where(ds["mask_2d"] > 0, float("nan"))
        ds["siconc"] = sea_ice_ocean

    if "LSRCc" in ds:
        sea_ice_ocean = xr.DataArray(
            rng.uniform(0.0, 0.2, size=ds["LSRCc"].shape),
            dims=ds["LSRCc"].dims,
            coords=ds["LSRCc"].coords,
        )
        if "mask_2d" in ds:
            sea_ice_ocean = sea_ice_ocean.where(ds["mask_2d"] > 0, float("nan"))
        ds["LSRCc"] = sea_ice_ocean

    if "LSNKc" in ds:
        sea_ice_ocean = xr.DataArray(
            1.5 * 905 + rng.uniform(0.0, 0.2, size=ds["LSNKc"].shape),
            dims=ds["LSNKc"].dims,
            coords=ds["LSNKc"].coords,
        )
        if "mask_2d" in ds:
            sea_ice_ocean = sea_ice_ocean.where(ds["mask_2d"] > 0, float("nan"))
        ds["LSNKc"] = sea_ice_ocean

    if "XPRTc" in ds:
        sea_ice_ocean = xr.DataArray(
            0.2 * 330 + rng.uniform(0.0, 0.05, size=ds["XPRTc"].shape),
            dims=ds["XPRTc"].dims,
            coords=ds["XPRTc"].coords,
        )
        if "mask_2d" in ds:
            sea_ice_ocean = sea_ice_ocean.where(ds["mask_2d"] > 0, float("nan"))
        ds["XPRTc"] = sea_ice_ocean

    ds.to_netcdf(filename, unlimited_dims=["time"])
    return ds


def _save_ice_scalar_stats_netcdf(
    filename: str,
    variable_names: list[str],
    kind: str,
):
    data_vars = {}
    for name in variable_names:
        if kind == "mean":
            if name == "siconc":
                value = 0.5
            elif name == "LSRCc":
                value = 7e-8
            elif name == "LSNKc":
                value = -3e-9
            elif name == "XPRTc":
                value = -6e-8
            else:
                value = 0.0
        elif kind == "std":
            if name == "siconc":
                value = 0.45
            elif name == "LSRCc":
                value = 5e-7
            elif name == "LSNKc":
                value = 6e-8
            elif name == "XPRTc":
                value = 5e-7
            else:
                value = 1.0
        else:
            raise ValueError(f"Unknown stats kind: {kind}")
        data_vars[name] = xr.DataArray(
            np.float64(value),
            attrs={"units": "m", "long_name": name},
        )
    xr.Dataset(data_vars=data_vars).to_netcdf(filename, format="NETCDF4_CLASSIC")


_TRAIN_CONFIG_TEMPLATE = """
experiment_dir: {results_dir}
save_checkpoint: true
save_per_epoch_diagnostics: {save_per_epoch_diagnostics}
max_epochs: {max_epochs}
logging:
  log_to_screen: true
  log_to_wandb: {log_to_wandb}
  log_to_file: false
  project: fme
  entity: ai2cm
train_loader:
  dataset:
    data_path: '{train_data_path}'
    spatial_dimensions: latlon
  batch_size: 2
  num_data_workers: 0
validation_loader:
  dataset:
    data_path: '{valid_data_path}'
    spatial_dimensions: latlon
  batch_size: 2
  num_data_workers: 0
optimization:
  use_gradient_accumulation: true
  optimizer_type: "Adam"
  lr: 0.001
  kwargs:
    weight_decay: 0.01
  scheduler:
      type: CosineAnnealingLR
      kwargs:
        T_max: 1
stepper_training:
  n_forward_steps: 2
  loss:
    type: "MSE"
stepper:
  input_masking:
    mask_value: 0
    fill_value: 0.0
  step:
    type: single_module
    config:
      in_names: {in_variable_names}
      out_names: {out_variable_names}
      normalization:
        network:
          global_means_path: '{global_means_path}'
          global_stds_path: '{global_stds_path}'
      builder:
        type: FloeNet
        config:
          latent_dimension: 4
          activation: SiLU
          meshes: 4
          M0: 4
          bias: true
          radius_fraction: 1
          layernorm: true
          processor_steps: 1
          residual: true
          is_ocean: true
      corrector:
        type: "ice_corrector"
        config:
          budget_correction:
            corrected_variables:
              siconc:
              - LSRCc
              - LSNKc
              - XPRTc
inference:
  aggregator:
    monthly_reference_data: {monthly_data_filename}
    log_step_means: []
  loader:
    dataset:
      data_path: '{valid_data_path}'
      spatial_dimensions: latlon
    start_indices:
      first: 0
      n_initial_conditions: 2
      interval: 1
  n_forward_steps: {inference_forward_steps}
  forward_steps_in_memory: 2
"""

_INFERENCE_CONFIG_TEMPLATE = """
experiment_dir: {results_dir}
n_forward_steps: 6
forward_steps_in_memory: 2
checkpoint_path: {results_dir}/training_checkpoints/best_ckpt.tar
data_writer:
  save_prediction_files: true
aggregator:
  log_video: false
  log_step_means: []
logging:
  log_to_screen: true
  log_to_wandb: {log_to_wandb}
  log_to_file: false
  project: fme
  entity: ai2cm
loader:
  dataset:
    data_path: '{valid_data_path}'
    spatial_dimensions: latlon
    fill_nans:
      method: constant
      value: 0.0
  start_indices:
    first: 0
    n_initial_conditions: 2
    interval: 1
validation:
  loader:
    dataset:
      data_path: '{valid_data_path}'
      spatial_dimensions: latlon
    batch_size: 2
  stepper_training:
    n_forward_steps: 2
  aggregator:
    log_snapshots: false
    log_mean_maps: false
"""


def _get_test_yaml_files(
    train_data_path,
    valid_data_path,
    monthly_data_filename,
    results_dir,
    global_means_path,
    global_stds_path,
    in_variable_names,
    out_variable_names,
    log_to_wandb=False,
    max_epochs=1,
    inference_forward_steps=2,
    save_per_epoch_diagnostics=False,
):
    train_config_content = _TRAIN_CONFIG_TEMPLATE

    train_string = train_config_content.format(
        train_data_path=train_data_path,
        valid_data_path=valid_data_path,
        monthly_data_filename=monthly_data_filename,
        results_dir=results_dir,
        global_means_path=global_means_path,
        global_stds_path=global_stds_path,
        in_variable_names=in_variable_names,
        out_variable_names=out_variable_names,
        log_to_wandb=str(log_to_wandb).lower(),
        max_epochs=max_epochs,
        inference_forward_steps=inference_forward_steps,
        save_per_epoch_diagnostics=str(save_per_epoch_diagnostics).lower(),
    )

    inference_string = _INFERENCE_CONFIG_TEMPLATE.format(
        results_dir=results_dir,
        log_to_wandb=str(log_to_wandb).lower(),
        valid_data_path=valid_data_path,  # Inference uses validation data path
    )

    with tempfile.NamedTemporaryFile(mode="w", delete=False, suffix=".yaml") as f_train:
        f_train.write(train_string)

    with tempfile.NamedTemporaryFile(
        mode="w", delete=False, suffix=".yaml"
    ) as f_inference:
        f_inference.write(inference_string)

    return f_train.name, f_inference.name


def get_ice_dim_sizes(n_lat=16, n_lon=32, n_time=3, nz_levels=1) -> DimSizes:
    return DimSizes(
        n_time=n_time,
        horizontal=LatLonCoordinates(
            lon=torch.arange(float(n_lon)),
            lat=torch.arange(float(n_lat)),
        ).loaded_sizes,
        nz_interface=nz_levels,
    )


def _setup(
    path,
    log_to_wandb=True,
    max_epochs=1,
    n_time=60,
    timestep_days=2,
    inference_forward_steps=10,
    save_per_epoch_diagnostics=True,
    nz_levels=1,
):
    if not path.exists():
        path.mkdir(parents=True, exist_ok=True)
    seed = 0
    np.random.seed(seed)
    torch.manual_seed(seed)

    # Ice-specific variable names
    in_variable_names = ["siconc", "LSRCc", "LSNKc", "XPRTc"]
    out_variable_names = ["siconc", "LSRCc", "LSNKc", "XPRTc"]

    # Add masks and idepths for data generation
    mask_names = ["mask_2d"]

    in_variable_names_for_data_gen = list(set(in_variable_names + mask_names))

    all_variable_names_for_data_gen = list(
        set(in_variable_names_for_data_gen + out_variable_names)
    )
    stats_variable_names = list(set(in_variable_names + out_variable_names))

    dim_sizes = get_ice_dim_sizes(n_time=n_time, nz_levels=nz_levels)

    data_dir = path / "data"
    stats_dir = path / "stats"
    results_dir = path / "results"
    data_dir.mkdir(exist_ok=True)
    stats_dir.mkdir(exist_ok=True)
    results_dir.mkdir(exist_ok=True)

    save_ice_nd_netcdf(
        filename=data_dir / "data.nc",
        dim_sizes=dim_sizes,
        variable_names=all_variable_names_for_data_gen,
        timestep_days=timestep_days,
    )
    _save_ice_scalar_stats_netcdf(
        stats_dir / "stats-mean.nc",
        variable_names=stats_variable_names,
        kind="mean",
    )
    _save_ice_scalar_stats_netcdf(
        stats_dir / "stats-stddev.nc",
        variable_names=stats_variable_names,
        kind="std",
    )

    train_config_filename, inference_config_filename = _get_test_yaml_files(
        train_data_path=data_dir,
        valid_data_path=data_dir,
        monthly_data_filename="null",
        results_dir=results_dir,
        global_means_path=stats_dir / "stats-mean.nc",
        global_stds_path=stats_dir / "stats-stddev.nc",
        in_variable_names=in_variable_names,
        out_variable_names=out_variable_names,
        log_to_wandb=log_to_wandb,
        max_epochs=max_epochs,
        inference_forward_steps=inference_forward_steps,
        save_per_epoch_diagnostics=save_per_epoch_diagnostics,
    )
    return train_config_filename, inference_config_filename


def test_train_and_inference(tmp_path, very_fast_only: bool):
    """Ensure that ACE Ice training and subsequent standalone inference run."""
    if very_fast_only:
        pytest.skip("Skipping non-fast tests")

    train_config, inference_config = _setup(tmp_path)

    with mock_wandb() as wandb:
        train_main(yaml_config=train_config)
        wandb_logs = wandb.get_logs()
        for log in wandb_logs:
            assert "inference/mean/forecast_step" not in log

    results_dir = tmp_path / "results"

    validation_output_dir = results_dir / "output" / "val" / "epoch_0001"
    assert validation_output_dir.exists()
    validation_diags = ["mean"]
    validation_map_diags = ["snapshot", "mean_map"]
    for diagnostic in validation_diags + validation_map_diags:
        diagnostic_output = validation_output_dir / f"{diagnostic}_diagnostics.nc"
        assert diagnostic_output.exists()
        ds = xr.open_dataset(diagnostic_output, decode_timedelta=False)
        assert len(ds) > 0
        for var in ds.data_vars:
            if diagnostic == "mean":
                assert not np.isnan(ds[var].values).any()
            else:
                # other
                assert not np.isnan(ds[var].values).all()
                assert np.isnan(ds[var].values).any()

    inline_inference_output_dir = results_dir / "output" / "inference" / "epoch_0001"
    assert inline_inference_output_dir.exists()
    for diagnostic in ("time_mean", "time_mean_norm"):
        diagnostic_output = inline_inference_output_dir / f"{diagnostic}_diagnostics.nc"
        assert diagnostic_output.exists()
        ds = xr.open_dataset(diagnostic_output, decode_timedelta=False)
        assert len(ds) > 0
        for var in ds.data_vars:
            assert not np.isnan(ds[var].values).all()
            assert np.isnan(ds[var].values).any()

    with mock_wandb() as wandb:
        wandb.configure(log_to_wandb=True)
        inference_evaluator_main(yaml_config=inference_config)
        wandb_logs = wandb.get_logs()

    all_inference_logs = {}
    for log in wandb_logs:
        all_inference_logs.update(log)

    assert "val/mean/loss" in all_inference_logs
    for var in ["siconc", "LSRCc", "LSNKc", "XPRTc"]:
        assert (
            f"val/mean/weighted_rmse/{var}" in all_inference_logs
        ), f"Expected val/mean/weighted_rmse/{var} in inference logs"
    validation_output_dir = results_dir / "validation"
    assert validation_output_dir.exists()

    tm_logs = wandb_logs[-1]
    for name, metric in tm_logs.items():
        if isinstance(metric, float):
            assert not np.isnan(metric), f"{name} should not be NaN"

    prediction_output_path = results_dir / "autoregressive_predictions.nc"
    best_checkpoint_path = results_dir / "training_checkpoints" / "best_ckpt.tar"
    assert prediction_output_path.exists()
    assert best_checkpoint_path.exists()

    ds_prediction = xr.open_dataset(prediction_output_path, decode_timedelta=False)
    for name in ["siconc", "LSRCc", "LSNKc", "XPRTc"]:
        assert name in ds_prediction
        # outputs should have some non-null values
        assert not np.isnan(ds_prediction[name].values).all()
        # outputs should have some masked regions
        assert np.isnan(ds_prediction[name].values).any()

    ds_target = xr.open_dataset(
        results_dir / "autoregressive_target.nc", decode_timedelta=False
    )
    assert "siconc" in ds_target

    for diagnostic in ("mean", "mean_norm"):
        diagnostic_output = results_dir / f"{diagnostic}_diagnostics.nc"
        assert diagnostic_output.exists()
        ds = xr.open_dataset(diagnostic_output, decode_timedelta=False)
        assert len(ds) > 0
        for var in ds.data_vars:
            assert not np.isnan(ds[var].values).any()
