repos:
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
      additional_dependencies: ["click==8.0.4"]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-added-large-files
      args: [--maxkb=250]
    - id: trailing-whitespace
    - id: flake8
      name: flake8
      language_version: python3
      exclude: "__init__.py"
      args: [--config, setup.cfg]
    - id: flake8
      name: flake8 __init__.py files
      files: "__init__.py"
      # ignore unused import error in __init__.py files
      args: ["--ignore=F401,E203,W503", --config, setup.cfg]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
    - id: mypy
      additional_dependencies: ["types-PyYaml==5.4.3"]
      args: [
          --follow-imports, silent, --ignore-missing-imports
        ]
      exclude: |
        (?x)^(
        .+/conf.py |
        .+/setup.py |
        .+/conftest.py
        )$
-   repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        name: isort (python)