from functools import partial
from collections import OrderedDict
from copy import Error, deepcopy
from re import S
from numpy.lib.arraypad import pad
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from apex.normalization import FusedLayerNorm
#from timm.data import IMAGENET_DEFAULT_MEAN, IMAGENET_DEFAULT_STD
#from timm.models.layers import trunc_normal_ #DropPath,
import torch.fft
from torch.nn.modules.container import Sequential
from torch.utils.checkpoint import checkpoint_sequential
#from einops import rearrange
from typing import Optional
import math

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.
    
    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)
        
    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)
        
        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)
        
        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()
        
        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)
                                                                                                                                
        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor
    
    
def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
    tensor: an n-dimensional `torch.Tensor`
    mean: the mean of the normal distribution
    std: the standard deviation of the normal distribution
    a: the minimum cutoff value
    b: the maximum cutoff value
    Examples:
    >>> w = torch.empty(3, 5)
    >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)



@torch.jit.script
def drop_path(x: torch.Tensor, drop_prob: float = 0., training: bool = False) -> torch.Tensor:
    """Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).
    This is the same as the DropConnect impl I created for EfficientNet, etc networks, however,
    the original name is misleading as 'Drop Connect' is a different form of dropout in a separate paper...
    See discussion: https://github.com/tensorflow/tpu/issues/494#issuecomment-532968956 ... I've opted for
    changing the layer and argument names to 'drop path' rather than mix DropConnect as a layer name and use
    'survival rate' as the argument.
    """
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1. - drop_prob
    shape = (x.shape[0],) + (1,) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = keep_prob + torch.rand(shape, dtype=x.dtype, device=x.device)
    random_tensor.floor_()  # binarize
    output = x.div(keep_prob) * random_tensor
    return output


class DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample  (when applied in main path of residual blocks).
    """
    def __init__(self, drop_prob=None):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob
        
    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training) 


class PatchEmbed(nn.Module):
    def __init__(self, img_size=(224, 224), patch_size=(16, 16), in_chans=3, embed_dim=768):
        super(PatchEmbed, self).__init__()
        num_patches = (img_size[1] // patch_size[1]) * (img_size[0] // patch_size[0])
        self.img_size = img_size
        self.patch_size = patch_size
        self.num_patches = num_patches
        self.proj = nn.Conv2d(in_chans, embed_dim, kernel_size=patch_size, stride=patch_size)
        
    def forward(self, x):
        # gather input
        B, C, H, W = x.shape
        assert H == self.img_size[0] and W == self.img_size[1], f"Input image size ({H}*{W}) doesn't match model ({self.img_size[0]}*{self.img_size[1]})."
        # new: B, C, H*W
        x = self.proj(x).flatten(2)
        return x

    
class PatchEmbed3D(nn.Module):
    def __init__(self, img_size=(224, 224), patch_size=(16, 16), in_chans=3, embed_dim=768):
        super(PatchEmbed3D, self).__init__()
        num_patches = (img_size[1] // patch_size[1]) * (img_size[0] // patch_size[0])
        self.img_size = img_size
        self.patch_size = patch_size
        self.num_patches = num_patches
        self.proj = nn.Conv3d(in_chans, embed_dim, kernel_size=(1, patch_size[0], patch_size[1]), stride=(1, patch_size[0], patch_size[1]))

    def forward(self, x):
        # gather input
        B, C, T, H, W = x.shape
        assert H == self.img_size[0] and W == self.img_size[1], f"Input image size ({H}*{W}) doesn't match model ({self.img_size[0]}*{self.img_size[1]})."
        # new: B, C, T, H*W
        x = self.proj(x).flatten(start_dim=3)
        return x  
    
    
class MLP(nn.Module):
    def __init__(self, in_features, hidden_features=None, out_features=None, act_layer=nn.GELU, drop=0.):
        super(MLP, self).__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        
        # first set of hp
        self.w1 = nn.Parameter(torch.ones(hidden_features, in_features, 1, 1))
        self.b1 = nn.Parameter(torch.zeros(hidden_features))
        
        # second set of hp
        self.w2 = nn.Parameter(torch.ones(out_features, hidden_features, 1, 1))
        self.b2 = nn.Parameter(torch.zeros(out_features))
        
        self.act = act_layer()
        self.drop = nn.Dropout(drop) if drop > 0. else nn.Identity()
        
        # init weights
        self._init_weights()

    def _init_weights(self):
        trunc_normal_(self.w1, std=.02)
        nn.init.constant_(self.b1, 0.)
        trunc_normal_(self.w2, std=.02)
        nn.init.constant_(self.b2, 0.)

        
    def forward(self, x):
        
        torch.cuda.nvtx.range_push("MLP")
        
        x = F.conv2d(x, self.w1, bias=self.b1)        
        x = self.act(x)
        x = self.drop(x)
        x = F.conv2d(x, self.w2, bias=self.b2)        
        x = self.drop(x)
        
        torch.cuda.nvtx.range_pop()
        
        return x 

    
class MLPv2(nn.Module):
    def __init__(self, in_features, hidden_features=None, out_features=None, act_layer=nn.GELU, drop=0.):
        super(MLPv2, self).__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Conv2d(in_features, hidden_features, 1, bias=True)
        self.act = act_layer()
        self.fc2 = nn.Conv2d(hidden_features, out_features, 1, bias=True)
        self.drop = nn.Dropout(drop) if drop > 0. else nn.Identity()
        
    def forward(self, x):
                        
        x = self.fc1(x)        
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        
        return x 

    
class MLP3Dv2(nn.Module):
    def __init__(self, in_features, hidden_features=None, out_features=None, act_layer=nn.GELU, drop=0.):
        super(MLP3Dv2, self).__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Conv3d(in_features, hidden_features, 1, bias=True)
        self.act = act_layer()
        self.fc2 = nn.Conv3d(hidden_features, out_features, 1, bias=True)
        self.drop = nn.Dropout(drop) if drop > 0. else nn.Identity()
        
    def forward(self, x):
        
        x = self.fc1(x)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        
        return x 
    
    
@torch.jit.script
def compl_mul_add_fwd(a: torch.Tensor, b: torch.Tensor, c: torch.Tensor) -> torch.Tensor:
    tmp = torch.einsum("bkixys,kior->srbkoxy", a, b)
    res = torch.stack([tmp[0,0,...] - tmp[1,1,...], tmp[1,0,...] + tmp[0,1,...]], dim=-1) + c
    return res


@torch.jit.script
def compl_mul_add_fwd_c(a: torch.Tensor, b: torch.Tensor, c: torch.Tensor) -> torch.Tensor:
    ac = torch.view_as_complex(a)
    bc = torch.view_as_complex(b)
    cc = torch.view_as_complex(c)
    tmp = torch.einsum("bkixy,kio->bkoxy", ac, bc)
    res = tmp + cc
    return torch.view_as_real(res)


class AFNO2Dv2(nn.Module):
    def __init__(self, hidden_size, num_blocks=8, sparsity_threshold=0.01, hard_thresholding_fraction=1, hidden_size_factor=1,
                 use_complex_kernels=False):
        super(AFNO2Dv2, self).__init__()
        assert hidden_size % num_blocks == 0, f"hidden_size {hidden_size} should be divisble by num_blocks {num_blocks}"
        
        self.hidden_size = hidden_size
        self.sparsity_threshold = sparsity_threshold
        self.num_blocks = num_blocks
        self.block_size = self.hidden_size // self.num_blocks
        self.hard_thresholding_fraction = hard_thresholding_fraction
        self.hidden_size_factor = hidden_size_factor
        self.scale = 0.02
        self.mult_handle = compl_mul_add_fwd_c if use_complex_kernels else compl_mul_add_fwd
        
        # new
        self.w1 = nn.Parameter(self.scale * torch.randn(self.num_blocks, self.block_size, self.block_size * self.hidden_size_factor, 2))
        self.b1 = nn.Parameter(self.scale * torch.randn(self.num_blocks, self.block_size * self.hidden_size_factor, 1, 1, 2))
        self.w2 = nn.Parameter(self.scale * torch.randn(self.num_blocks, self.block_size * self.hidden_size_factor, self.block_size, 2))
        self.b2 = nn.Parameter(self.scale * torch.randn(self.num_blocks, self.block_size, 1, 1, 2))
        
    def forward(self, x):
        bias = x
        
        dtype = x.dtype
        x = x.float()
        B, C, H, W = x.shape
        total_modes = H // 2 + 1
        kept_modes = int(total_modes * self.hard_thresholding_fraction)
        
        x = torch.fft.rfft2(x, dim=(-2, -1), norm="ortho")
        x = x.view(B, self.num_blocks, self.block_size, H, W // 2 + 1)
        
        # do spectral conv
        x = torch.view_as_real(x)
        o2 = torch.zeros(x.shape, device=x.device)
        
        o1 = F.relu(self.mult_handle(x[:, :, :, total_modes-kept_modes:total_modes+kept_modes, :kept_modes, :], self.w1, self.b1))
        o2[:, :, :, total_modes-kept_modes:total_modes+kept_modes, :kept_modes, :] = self.mult_handle(o1, self.w2, self.b2)
        
        # finalize
        x = F.softshrink(o2, lambd=self.sparsity_threshold)
        x = torch.view_as_complex(x)
        x = x.reshape(B, C, H, W // 2 + 1)
        x = torch.fft.irfft2(x, s=(H, W), dim=(-2,-1), norm="ortho")
        x = x.type(dtype)
    
        return x + bias

    
@torch.jit.script
def compl_mul_add_fwd_3d(a: torch.Tensor, b: torch.Tensor, c: torch.Tensor) -> torch.Tensor:
    tmp = torch.einsum("bkitxys,kiotr->srbkotxy", a, b)
    res = torch.stack([tmp[0,0,...] - tmp[1,1,...], tmp[1,0,...] + tmp[0,1,...]], dim=-1) + c
    return res


@torch.jit.script
def compl_mul_add_fwd_3d_c(a: torch.Tensor, b: torch.Tensor, c: torch.Tensor) -> torch.Tensor:
    ac = torch.view_as_complex(a)
    bc = torch.view_as_complex(b)
    cc = torch.view_as_complex(c)
    tmp = torch.einsum("bkitxy,kiot->bkotxy", ac, bc)
    res = tmp + cc
    return torch.view_as_real(res) 
    
    
# we expect data to be in BCTHW format
class AFNO3Dv2(nn.Module):
    def __init__(self, hidden_size, time_window=56, num_blocks=8, sparsity_threshold=0.01,
                 hard_thresholding_fraction=1, hidden_size_factor=1,
                 use_complex_kernels=False):
        super(AFNO3Dv2, self).__init__()

        self.hidden_size = hidden_size
        self.time_window = time_window
        self.sparsity_threshold = sparsity_threshold
        self.num_blocks = num_blocks
        self.block_size = self.hidden_size // self.num_blocks
        self.hard_thresholding_fraction = hard_thresholding_fraction
        self.hidden_size_factor = hidden_size_factor
        self.scale = 0.02
        self.mult_handle = compl_mul_add_fwd_3d_c if use_complex_kernels else compl_mul_add_fwd_3d
        
        # new
        self.w1 = nn.Parameter(self.scale * torch.randn(self.num_blocks, self.block_size, self.block_size * self.hidden_size_factor, self.time_window, 2))
        self.b1 = nn.Parameter(self.scale * torch.randn(self.num_blocks, self.block_size * self.hidden_size_factor, self.time_window, 1, 1, 2))
        self.w2 = nn.Parameter(self.scale * torch.randn(self.num_blocks, self.block_size * self.hidden_size_factor, self.block_size, self.time_window, 2))
        self.b2 = nn.Parameter(self.scale * torch.randn(self.num_blocks, self.block_size, self.time_window, 1, 1, 2))
        
    def forward(self, x):
        bias = x
        
        dtype = x.dtype
        x = x.float()
        B, C, T, H, W = x.shape
        total_modes = H // 2 + 1
        kept_modes = int(total_modes * self.hard_thresholding_fraction)
        
        x = torch.fft.rfftn(x, dim=(-3, -2, -1), norm="ortho")
        x = x.view(B, self.num_blocks, self.block_size, T, H, W // 2 + 1)
        
        # do spectral conv
        x = torch.view_as_real(x)
        o2 = torch.zeros(x.shape, device=x.device)

        o1 = F.relu(self.mult_handle(x[:, :, :, :, total_modes-kept_modes:total_modes+kept_modes, :kept_modes, :], self.w1, self.b1))
        o2[:, :, :, :, total_modes-kept_modes:total_modes+kept_modes, :kept_modes, :] = self.mult_handle(o1, self.w2, self.b2)
        
        # finalize
        x = F.softshrink(o2, lambd=self.sparsity_threshold)
        x = torch.view_as_complex(x)
        x = x.reshape(B, C, T, H, W // 2 + 1)
        x = torch.fft.irfftn(x, s=(T, H, W), dim=(-3, -2, -1), norm="ortho")
        x = x.type(dtype)
        
        return x + bias  
