checkpoint_path: /ckpt.tar
allow_incompatible_dataset: true
data_writer:
  save_monthly_files: false
  save_prediction_files: false
experiment_dir: /results
forward_steps_in_memory: 40
n_forward_steps: 10
initial_condition:
  path: /climate-default/2026-02-18-era5-1deg-combined-aimip-forcing-1978-2022.zarr
  engine: zarr
  start_indices:
    times:
      - '1978-10-01T00:00:00'
forcing_loader:
  dataset:
    data_path: /climate-default
    file_pattern: 2026-02-18-era5-1deg-combined-aimip-forcing-1978-2022.zarr
    engine: zarr
    fill_nans:
        method: constant
        value: 0.0
        zonal_interp_variables:
          - sea_surface_temperature
  num_data_workers: 8
  perturbations:
    sst:
      - type: constant
        config:
          amplitude: 0.0
          ocean_fraction_cutoff: null
logging:
  project: ace
stepper_override:
  ocean:
    surface_temperature_name: sea_surface_temperature
    ocean_fraction_name: mask_sea_surface_temperature
    # Allow checkpoint trained without ocean; prescribed SST (e.g. perturbed) is
    # injected into step output for next-step input. Hacky; for perturbation only.
    allow_missing_in_model: true
