import abc
import logging
from collections.abc import Callable, Iterator
from typing import cast, final

import numpy as np
import torch

from fme.ace.data_loading.batch_data import BatchData
from fme.core.dataset.dataset import DatasetItem
from fme.core.dataset.schedule import IntSchedule
from fme.core.distributed import Distributed
from fme.core.generics.dataloader import GenericDataLoader
from fme.core.generics.dataset import GenericDataset
from fme.core.rand import alternate_seed


def get_data_loader(
    dataset: GenericDataset[DatasetItem],
    batch_size: int,
    n_window_timesteps: IntSchedule,
    time_buffer: int,
    time_buffer_pool_size: int,
    num_workers: int,
    sampler: torch.utils.data.Sampler,
    shuffled: bool,
    drop_last: bool,
    pin_memory: bool,
    collate_fn: Callable[[list[DatasetItem]], BatchData],
    multiprocessing_context: str | None,
    persistent_workers: bool,
    prefetch_factor: int | None,
) -> "DataLoaderABC":
    if prefetch_factor is None:
        # DataLoader default is not None so we must leave it unset
        kwargs = {}
    else:
        kwargs = {"prefetch_factor": prefetch_factor}
    torch_dataloader = TorchDataLoader(
        dataset,
        collate_fn,
        batch_size=batch_size,
        num_workers=num_workers,
        sampler=sampler,
        drop_last=drop_last,
        pin_memory=pin_memory,
        multiprocessing_context=multiprocessing_context,
        persistent_workers=persistent_workers,
        **kwargs,
    )
    dataloader: DataLoaderABC
    if time_buffer > 0:
        dataloader = SlidingWindowDataLoader(
            loader=torch_dataloader,
            output_n_timesteps=n_window_timesteps,
            time_buffer=time_buffer,
            shuffle=shuffled,
            pool_size=time_buffer_pool_size,
        )
    else:
        dataloader = torch_dataloader

    if len(dataloader) == 0:
        msg = (
            "No batches in dataloader: "
            f"{dataloader.n_samples} samples, "
            f"batch size is {dataloader.batch_size}"
        )
        if time_buffer > 0:
            msg += f", and time_buffer is {time_buffer}"
        raise ValueError(msg)

    return dataloader


class DataLoaderABC(abc.ABC):
    @abc.abstractmethod
    def __iter__(self) -> Iterator[BatchData]:
        pass

    @abc.abstractmethod
    def __len__(self) -> int:
        pass

    @abc.abstractmethod
    def __next__(self) -> BatchData:
        pass

    @property
    @abc.abstractmethod
    def batch_size(self) -> int:
        """
        Number of samples in a single batch.
        """
        pass

    @property
    @abc.abstractmethod
    def n_samples(self) -> int:
        pass

    @property
    @final
    def n_batches(self) -> int:
        # Note this method is not (at time of writing) used and has the same meaning
        # as __len__, it exists only so that the meaning of the n_samples property
        # is unambiguous. Previously there have been bugs caused by confusion between
        # the two.
        return len(self)

    @abc.abstractmethod
    def log_info(self, name: str):
        pass

    @abc.abstractmethod
    def subset(
        self, start_batch: int | None = None, stop_batch: int | None = None
    ) -> "DataLoaderABC":
        """
        Return a subset of the data loader starting at the given batch index
        and stopping at the given batch index (exclusive).

        Args:
            start_batch: Index of the first batch to include.
            stop_batch: Index of the last batch to include (exclusive).

        Returns:
            A subset of the data loader.
        """
        pass

    @abc.abstractmethod
    def set_epoch(self, epoch: int):
        pass

    @abc.abstractmethod
    def alternate_shuffle(self):
        """
        Change the random shuffle of the data loader for the current epoch.
        """
        pass


class TorchDataLoader(GenericDataLoader[BatchData], DataLoaderABC):
    pass


def random_columns_no_replacement(N, M, seed=None):
    """
    Return an (N, M) int array.
    Each column is an independent random permutation of range(N).
    """
    rng = np.random.default_rng(seed)
    return np.argsort(rng.random((N, M), dtype=np.float32), axis=1)


def build_pool_schedule(
    n_input_batches: int,
    n_sub_batches: int,
    pool_size: int,
    shuffle: bool,
    seed: int,
) -> np.ndarray:
    """Build a deterministic schedule for the pooled sliding window.

    Returns an (N, 2) int32 array where each row is
    (input_batch_idx, sub_window_offset).  The schedule is generated by
    simulating a pool of ``pool_size`` slots.  Output batches are drawn by
    selecting a pool slot, then a sub-window within that slot.  When a slot
    is fully consumed it is replaced by the next input batch.

    Args:
        n_input_batches: Total number of input (fat) batches.
        n_sub_batches: Number of sub-window offsets per input batch.
        pool_size: Number of input batches to hold simultaneously.
        shuffle: If True, both slot selection and sub-window selection are
            randomized. If False, slot selection is round-robin and
            sub-windows are sequential.
        seed: RNG seed for deterministic generation.
    """
    total = n_input_batches * n_sub_batches
    schedule = np.empty((total, 2), dtype=np.int32)
    rng = np.random.default_rng(seed)

    # pool entries: (input_batch_idx, list_of_remaining_offsets)
    pool: list[tuple[int, list[int]]] = []
    next_input = 0

    for _ in range(min(pool_size, n_input_batches)):
        pool.append((next_input, list(range(n_sub_batches))))
        next_input += 1

    robin = 0
    for pos in range(total):
        if shuffle:
            slot_idx = int(rng.integers(len(pool)))
        else:
            slot_idx = robin % len(pool)

        input_idx, offsets = pool[slot_idx]

        if shuffle:
            offset_pos = int(rng.integers(len(offsets)))
        else:
            offset_pos = 0
        offset = offsets.pop(offset_pos)

        schedule[pos, 0] = input_idx
        schedule[pos, 1] = offset

        if not offsets:
            pool.pop(slot_idx)
            if next_input < n_input_batches:
                pool.append((next_input, list(range(n_sub_batches))))
                next_input += 1
            robin = slot_idx
        else:
            pool[slot_idx] = (input_idx, offsets)
            robin = slot_idx + 1

    return schedule


class SlidingWindowDataLoader(DataLoaderABC):
    """
    A wrapper for the torch data loader that provides additional properties.
    Create more batches by applying a sliding window to existing batches.

    When ``pool_size`` > 1, multiple input batches are held in memory
    simultaneously and output batches are interleaved across them,
    reducing the temporal correlation between consecutive outputs.
    """

    def __init__(
        self,
        loader: TorchDataLoader,
        output_n_timesteps: IntSchedule,
        time_buffer: int,
        shuffle: bool,
        pool_size: int = 1,
        # pool_size == 1 subset parameters (backward compat):
        n_skipped_input_batches: int = 0,
        skip_first_n_output_batches: int = 0,
        skip_last_n_output_batches: int = 0,
        # pool_size > 1 subset parameters:
        _total_input_batches: int | None = None,
        _schedule_start: int = 0,
        _schedule_stop: int | None = None,
        _loader_start_idx: int = 0,
    ):
        self._input_loader_len = len(loader)
        self._loader = loader
        self._input_n_timesteps_schedule = output_n_timesteps.add(time_buffer)
        self._n_new_batches = time_buffer + 1
        self._time_buffer = time_buffer
        self._output_n_timesteps_schedule = output_n_timesteps
        self._pool_size = pool_size

        # pool_size == 1 state
        self._shuffle = shuffle
        self._n_skipped_input_batches = n_skipped_input_batches
        self._i_batch = self._n_skipped_input_batches
        self._skip_first_n_output_batches = skip_first_n_output_batches
        self._skip_last_n_output_batches = skip_last_n_output_batches
        self._current_batch: BatchData | None = None

        # pool_size > 1 state
        self._total_input_batches = (
            _total_input_batches
            if _total_input_batches is not None
            else self._input_loader_len
        )
        self._schedule_start = _schedule_start
        self._schedule_stop = _schedule_stop
        self._loader_start_idx = _loader_start_idx

        self._update_n_timesteps_for_epoch(0)
        self.set_epoch(0)

    # ---- shared helpers ----

    def _update_n_timesteps_for_epoch(self, epoch: int):
        self._input_n_timesteps = self._input_n_timesteps_schedule.get_value(epoch)
        self._output_n_timesteps = self._output_n_timesteps_schedule.get_value(epoch)
        assert self._output_n_timesteps <= self._input_n_timesteps
        self._stored_shuffle_indices = None
        self._stored_schedule = None
        self._stored_slice_last_use: dict[int, int] | None = None

    # ---- pool_size == 1 helpers (unchanged from original) ----

    @property
    def _shuffle_indices(self):
        if self._stored_shuffle_indices is None:
            if self._shuffle:
                self._stored_shuffle_indices = torch.from_numpy(
                    random_columns_no_replacement(
                        self._n_skipped_input_batches + self._input_loader_len,
                        self._n_new_batches,
                        seed=self._seed,
                    )
                )
            else:
                self._stored_shuffle_indices = torch.arange(self._n_new_batches)[
                    None, :
                ].broadcast_to(
                    (
                        self._n_skipped_input_batches + self._input_loader_len,
                        self._n_new_batches,
                    )
                )
        return self._stored_shuffle_indices

    # ---- pool_size > 1 helpers ----

    @property
    def _schedule(self) -> np.ndarray:
        if self._stored_schedule is None:
            self._stored_schedule = build_pool_schedule(
                n_input_batches=self._total_input_batches,
                n_sub_batches=self._n_new_batches,
                pool_size=self._pool_size,
                shuffle=self._shuffle,
                seed=self._seed,
            )
        return self._stored_schedule

    @property
    def _slice_last_use(self) -> dict[int, int]:
        if self._stored_slice_last_use is None:
            stop = (
                self._schedule_stop
                if self._schedule_stop is not None
                else len(self._schedule)
            )
            last_use: dict[int, int] = {}
            for i in range(self._schedule_start, stop):
                last_use[int(self._schedule[i, 0])] = i
            self._stored_slice_last_use = last_use
        return self._stored_slice_last_use

    # ---- DataLoaderABC implementation ----

    def __iter__(self) -> Iterator[BatchData]:
        if self._pool_size > 1:
            self._loaditer = iter(self._loader)
            self._cache: dict[int, BatchData] = {}
            self._next_loader_idx = self._loader_start_idx
            self._schedule_pos = self._schedule_start
        else:
            self._loaditer = iter(self._loader)
            self._i_batch = self._n_skipped_input_batches
            try:
                self._current_batch = next(self._loaditer).to_device()
            except StopIteration:
                return iter([])
            self._counter = self._skip_first_n_output_batches
        return self

    def __len__(self) -> int:
        if self._pool_size > 1:
            stop = (
                self._schedule_stop
                if self._schedule_stop is not None
                else self._total_input_batches * self._n_new_batches
            )
            return stop - self._schedule_start
        return self._input_loader_len * self._n_new_batches

    def __next__(self) -> BatchData:
        if self._pool_size > 1:
            return self._next_pooled()
        return self._next_single()

    def _next_single(self) -> BatchData:
        if self._current_batch is None:
            self._current_batch = next(self._loaditer).to_device()
            self._i_batch += 1
            self._counter = 0
            assert self._current_batch.n_timesteps == self._input_n_timesteps
        start = self._shuffle_indices[self._i_batch, self._counter]
        slice_ = slice(start, start + self._output_n_timesteps)
        small_batch = self._current_batch.select_time_slice(slice_)
        self._counter += 1
        if self._counter == self._n_new_batches:
            self._current_batch = None
        if self._i_batch == self._input_loader_len - 1:
            if self._counter == self._n_new_batches - self._skip_last_n_output_batches:
                self._current_batch = None
        return small_batch

    def _next_pooled(self) -> BatchData:
        stop = (
            self._schedule_stop
            if self._schedule_stop is not None
            else len(self._schedule)
        )
        if self._schedule_pos >= stop:
            raise StopIteration

        input_idx = int(self._schedule[self._schedule_pos, 0])
        offset = int(self._schedule[self._schedule_pos, 1])

        while input_idx not in self._cache:
            batch = next(self._loaditer).to_device()
            assert batch.n_timesteps == self._input_n_timesteps
            self._cache[self._next_loader_idx] = batch
            self._next_loader_idx += 1

        fat_batch = self._cache[input_idx]
        slice_ = slice(offset, offset + self._output_n_timesteps)
        small_batch = fat_batch.select_time_slice(slice_)

        if self._slice_last_use[input_idx] <= self._schedule_pos:
            del self._cache[input_idx]

        self._schedule_pos += 1
        return small_batch

    @property
    def batch_size(self) -> int:
        return self._loader.batch_size

    @property
    def n_samples(self) -> int:
        return self._loader.n_samples

    def _n_samples_per_dataset_item(self) -> int:
        return self._n_new_batches

    def log_info(self, name: str):
        logging.info(
            f"{name} data: {len(self) * self.batch_size} samples, {len(self)} batches"
        )
        if self._pool_size > 1:
            logging.info(
                f"{name} data: pool_size={self._pool_size}, "
                f"{self._n_new_batches} sub-batches per window, "
                "coming from the following base loader:"
            )
        else:
            logging.info(
                f"{name} data: An outer window size of "
                f"{self._n_samples_per_dataset_item()} samples was used to load "
                "the above samples and batches in chunks, coming from the following "
                "base loader:"
            )
        self._loader.log_info(name + " (base loader)")

    def subset(
        self, start_batch: int | None = None, stop_batch: int | None = None
    ) -> "SlidingWindowDataLoader":
        if start_batch is None and stop_batch is None:
            return self
        if self._pool_size > 1:
            return self._subset_pooled(start_batch, stop_batch)
        return self._subset_single(start_batch, stop_batch)

    def _subset_single(
        self, start_batch: int | None, stop_batch: int | None
    ) -> "SlidingWindowDataLoader":
        sub_batches_per_contained_batch = (
            1 + self._input_n_timesteps - self._output_n_timesteps
        )
        n_batches_to_skip, n_sub_batches_to_skip = get_skip_batches(
            sub_batches_per_contained_batch, start_batch
        )
        n_batches_to_stop, n_sub_batches_to_skip_last = get_stop_batches(
            sub_batches_per_contained_batch, stop_batch
        )
        subsetted_loader = self._loader.subset(
            start_batch=n_batches_to_skip, stop_batch=n_batches_to_stop
        )
        self._loaditer = iter(subsetted_loader)
        loader = SlidingWindowDataLoader(
            cast(TorchDataLoader, subsetted_loader),
            output_n_timesteps=self._output_n_timesteps_schedule,
            time_buffer=self._time_buffer,
            shuffle=self._shuffle,
            n_skipped_input_batches=n_batches_to_skip,
            skip_first_n_output_batches=n_sub_batches_to_skip,
            skip_last_n_output_batches=n_sub_batches_to_skip_last,
        )
        loader.set_epoch(self._epoch)
        return loader

    def _subset_pooled(
        self, start_batch: int | None, stop_batch: int | None
    ) -> "SlidingWindowDataLoader":
        schedule = self._schedule
        new_start = self._schedule_start + (start_batch or 0)
        new_stop: int | None
        if stop_batch is not None:
            new_stop = self._schedule_start + stop_batch
        else:
            new_stop = self._schedule_stop

        effective_stop = new_stop if new_stop is not None else len(schedule)
        needed_indices = schedule[new_start:effective_stop, 0]

        if len(needed_indices) == 0:
            min_input_idx = 0
            max_input_idx = 0
        else:
            min_input_idx = int(needed_indices.min())
            max_input_idx = int(needed_indices.max())

        # Subset underlying loader relative to its current start offset
        relative_start = min_input_idx - self._loader_start_idx
        relative_stop = max_input_idx + 1 - self._loader_start_idx
        subsetted_loader = self._loader.subset(
            start_batch=relative_start, stop_batch=relative_stop
        )

        loader = SlidingWindowDataLoader(
            cast(TorchDataLoader, subsetted_loader),
            output_n_timesteps=self._output_n_timesteps_schedule,
            time_buffer=self._time_buffer,
            shuffle=self._shuffle,
            pool_size=self._pool_size,
            _total_input_batches=self._total_input_batches,
            _schedule_start=new_start,
            _schedule_stop=new_stop,
            _loader_start_idx=min_input_idx,
        )
        loader.set_epoch(self._epoch)
        return loader

    def set_epoch(self, epoch: int):
        self._epoch = epoch
        dist = Distributed.get_instance()
        self._seed = self._epoch + dist.get_seed()
        self._loader.set_epoch(epoch)
        self._update_n_timesteps_for_epoch(epoch)

    def alternate_shuffle(self):
        self._loader.alternate_shuffle()
        self._seed = alternate_seed(self._seed)
        self._stored_shuffle_indices = None
        self._stored_schedule = None
        self._stored_slice_last_use = None


def get_skip_batches(
    sub_batches_per_contained_batch: int, start: int | None = None
) -> tuple[int, int]:
    """
    Get the number of batches and sub-batches to skip.

    Args:
        sub_batches_per_contained_batch: Number of sub-batches per contained batch.
        batch_size: Size of the batch.
        start: Number of samples (not batches) to skip.

    Returns:
        Number of batches to skip and number of sub-batches to skip.
    """
    if start is None:
        n_batches_to_skip = 0
        n_sub_batches_to_skip = 0
    else:
        n_batches_to_skip = start // sub_batches_per_contained_batch
        n_sub_batches_to_skip = start % sub_batches_per_contained_batch
    return n_batches_to_skip, n_sub_batches_to_skip


def get_stop_batches(
    sub_batches_per_contained_batch: int, stop: int | None = None
) -> tuple[int | None, int]:
    """
    Get the number of batches and sub-batches to stop.

    Args:
        sub_batches_per_contained_batch: Number of sub-batches per contained batch.
        batch_size: Size of the batch.
        stop: Number of batches to stop at (exclusive).

    Returns:
        Number of batches to stop at (exclusive)
        and which sub-batch to stop at (exclusive).
    """
    if stop is None:
        n_batches_to_stop: int | None = None
        n_sub_batches_to_skip_last = 0
    else:
        n_batches_to_stop = (stop - 1) // sub_batches_per_contained_batch + 1
        n_sub_batches_to_skip_last = (
            sub_batches_per_contained_batch - stop % sub_batches_per_contained_batch
        ) % sub_batches_per_contained_batch
    return n_batches_to_stop, n_sub_batches_to_skip_last
