from collections.abc import Callable, Iterator
from typing import Generic, Protocol, TypeVar

import numpy as np

TIn = TypeVar("TIn")
TOut = TypeVar("TOut")
_T = TypeVar("_T")


class Subsettable(Protocol[_T]):
    def __iter__(self) -> Iterator[_T]: ...
    def __len__(self) -> int: ...
    def subset(
        self,
        start_batch: int | None = None,
        stop_batch: int | None = None,
    ) -> "Subsettable[_T]": ...


def build_pool_schedule(
    n_input_batches: int,
    n_sub_batches: int,
    pool_size: int,
    shuffle: bool,
    seed: int,
) -> np.ndarray:
    """Build a deterministic schedule for the pooled sliding window.

    Returns an (N, 2) int32 array where each row is
    (input_batch_idx, sub_window_offset).  The schedule is generated by
    simulating a pool of ``pool_size`` slots.  Output batches are drawn by
    selecting a pool slot, then a sub-window within that slot.  When a slot
    is fully consumed it is replaced by the next input batch.

    Args:
        n_input_batches: Total number of input (fat) batches.
        n_sub_batches: Number of sub-window offsets per input batch.
        pool_size: Number of input batches to hold simultaneously.
        shuffle: If True, both slot selection and sub-window selection are
            randomized. If False, slot selection is round-robin and
            sub-windows are sequential.
        seed: RNG seed for deterministic generation.
    """
    total = n_input_batches * n_sub_batches
    schedule = np.empty((total, 2), dtype=np.int32)
    rng = np.random.default_rng(seed)

    # pool entries: (input_batch_idx, list_of_remaining_offsets)
    pool: list[tuple[int, list[int]]] = []
    next_input = 0

    for _ in range(min(pool_size, n_input_batches)):
        pool.append((next_input, list(range(n_sub_batches))))
        next_input += 1

    robin = 0
    for pos in range(total):
        if shuffle:
            slot_idx = int(rng.integers(len(pool)))
        else:
            slot_idx = robin % len(pool)

        input_idx, offsets = pool[slot_idx]

        if shuffle:
            offset_pos = int(rng.integers(len(offsets)))
        else:
            offset_pos = 0
        offset = offsets.pop(offset_pos)

        schedule[pos, 0] = input_idx
        schedule[pos, 1] = offset

        if not offsets:
            pool.pop(slot_idx)
            if next_input < n_input_batches:
                pool.append((next_input, list(range(n_sub_batches))))
                next_input += 1
            robin = slot_idx
        else:
            pool[slot_idx] = (input_idx, offsets)
            robin = slot_idx + 1

    return schedule


class _PoolItem(Generic[TIn]):
    __slots__ = ("data", "remaining_uses")

    def __init__(self, data: TIn, remaining_uses: int):
        self.data = data
        self.remaining_uses = remaining_uses


class PooledSequence(Generic[TIn, TOut]):
    """Yields sub-items from a fixed-size pool of source items.

    Maintains a pool of at most ``pool_size`` source items in memory.
    Sub-items are yielded according to a pre-built schedule. When all
    scheduled uses of a source item have been served, it is evicted
    from the pool and replaced by the next source item.

    The source must support iteration, ``__len__``, and
    ``subset(start_batch, stop_batch)``.

    Args:
        source: Iterable of source items supporting ``subset``.
        schedule: ``(N, 2)`` int32 array of ``(source_index, sub_item_offset)``.
        pool_size: Maximum number of source items held simultaneously.
        extract: ``(source_item, offset) -> sub_item``.
        prepare: Transform applied to a source item before caching
            (e.g. transfer to device). Only called for items that will
            be used by the schedule.
    """

    def __init__(
        self,
        source: Subsettable[TIn],
        schedule: np.ndarray,
        pool_size: int,
        extract: Callable[[TIn, int], TOut],
        prepare: Callable[[TIn], TIn] | None = None,
        _schedule_start: int = 0,
        _schedule_stop: int | None = None,
        _source_start_idx: int = 0,
    ):
        self._source = source
        self._schedule = schedule
        self._pool_size = pool_size
        self._extract = extract
        self._prepare = prepare if prepare is not None else _identity
        self._schedule_start = _schedule_start
        self._schedule_stop = _schedule_stop
        self._source_start_idx = _source_start_idx
        self._stored_use_counts: dict[int, int] | None = None

    @property
    def _effective_stop(self) -> int:
        if self._schedule_stop is not None:
            return self._schedule_stop
        return len(self._schedule)

    @property
    def _use_counts(self) -> dict[int, int]:
        if self._stored_use_counts is None:
            counts: dict[int, int] = {}
            for i in range(self._schedule_start, self._effective_stop):
                idx = int(self._schedule[i, 0])
                counts[idx] = counts.get(idx, 0) + 1
            self._stored_use_counts = counts
        return self._stored_use_counts

    def __len__(self) -> int:
        return self._effective_stop - self._schedule_start

    def __iter__(self) -> Iterator[TOut]:
        self._source_iter = iter(self._source)
        self._pool: dict[int, _PoolItem[TIn]] = {}
        self._next_source_idx = self._source_start_idx
        self._pos = self._schedule_start
        return self

    def __next__(self) -> TOut:
        if self._pos >= self._effective_stop:
            raise StopIteration

        source_idx = int(self._schedule[self._pos, 0])
        offset = int(self._schedule[self._pos, 1])

        while source_idx not in self._pool:
            item = next(self._source_iter)
            if self._next_source_idx in self._use_counts:
                assert len(self._pool) < self._pool_size
                self._pool[self._next_source_idx] = _PoolItem(
                    data=self._prepare(item),
                    remaining_uses=self._use_counts[self._next_source_idx],
                )
            self._next_source_idx += 1

        pool_item = self._pool[source_idx]
        result = self._extract(pool_item.data, offset)

        pool_item.remaining_uses -= 1
        if pool_item.remaining_uses == 0:
            del self._pool[source_idx]

        self._pos += 1
        return result

    def subset(
        self, start: int | None = None, stop: int | None = None
    ) -> "PooledSequence[TIn, TOut]":
        if start is None and stop is None:
            return self

        new_start = self._schedule_start + (start or 0)
        new_stop: int | None
        if stop is not None:
            new_stop = min(self._schedule_start + stop, self._effective_stop)
        else:
            new_stop = self._schedule_stop

        effective_stop = new_stop if new_stop is not None else len(self._schedule)
        needed_indices = self._schedule[new_start:effective_stop, 0]

        if len(needed_indices) == 0:
            subsetted_source = self._source.subset(start_batch=0, stop_batch=0)
            min_source_idx = self._source_start_idx
        else:
            min_source_idx = int(needed_indices.min())
            max_source_idx = int(needed_indices.max())
            relative_start = min_source_idx - self._source_start_idx
            relative_stop = max_source_idx + 1 - self._source_start_idx
            subsetted_source = self._source.subset(
                start_batch=relative_start, stop_batch=relative_stop
            )

        return PooledSequence(
            source=subsetted_source,
            schedule=self._schedule,
            pool_size=self._pool_size,
            extract=self._extract,
            prepare=self._prepare,
            _schedule_start=new_start,
            _schedule_stop=new_stop,
            _source_start_idx=min_source_idx,
        )


def _identity(x):
    return x
