experiment_dir: /results
save_checkpoint: true
checkpoint_every_n_batches: 100
log_train_every_n_batches: 10
validate_using_ema: true
ema:
  decay: 0.999
max_epochs: 20
n_coupled_steps: 4
inference:
  n_coupled_steps: <N_COUPLED_STEPS>
  coupled_steps_in_memory: 8
  loader:
    num_data_workers: 1
    dataset:
      ocean:
        merge:
        - data_path: /climate-default
          file_pattern: <COUPLED_OCEAN_ZARR>
          engine: zarr
        - data_path: /climate-default
          file_pattern: <OCEAN_ZARR>
          engine: zarr
      atmosphere:
        merge:
        - data_path: /climate-default
          file_pattern: <COUPLED_ATMOS_ZARR>
          engine: zarr
        - data_path: /climate-default
          file_pattern: <ATMOS_ZARR>
          engine: zarr
    start_indices:
      times: <INFERENCE_TIMES>
  aggregator:
    log_zonal_mean_images: false
    log_histograms: false
logging:
  log_to_screen: true
  log_to_wandb: true
  log_to_file: true
  project: <WANDB_PROJECT>
  entity: ai2cm
train_loader:
  batch_size: 16
  num_data_workers: 4
  prefetch_factor: 1
  dataset:
    - ocean:
        merge:
        - data_path: /climate-default
          file_pattern: <COUPLED_OCEAN_ZARR>
          engine: zarr
          subset: <TRAIN_SUBSET>
        - data_path: /climate-default
          file_pattern: <OCEAN_ZARR>
          engine: zarr
          subset: <TRAIN_SUBSET>
      atmosphere:
        merge:
        - data_path: /climate-default
          file_pattern: <COUPLED_ATMOS_ZARR>
          engine: zarr
          subset: <TRAIN_SUBSET>
        - data_path: /climate-default
          file_pattern: <ATMOS_ZARR>
          engine: zarr
          subset: <TRAIN_SUBSET>
validation_loader:
  batch_size: 16
  num_data_workers: 4
  prefetch_factor: 1
  dataset:
    - ocean:
        merge:
        - data_path: /climate-default
          file_pattern: <COUPLED_OCEAN_ZARR>
          engine: zarr
          subset: <VALIDATION_SUBSET>
        - data_path: /climate-default
          file_pattern: <OCEAN_ZARR>
          engine: zarr
          subset: <VALIDATION_SUBSET>
      atmosphere:
        merge:
        - data_path: /climate-default
          file_pattern: <COUPLED_ATMOS_ZARR>
          engine: zarr
          subset: <VALIDATION_SUBSET>
        - data_path: /climate-default
          file_pattern: <ATMOS_ZARR>
          engine: zarr
          subset: <VALIDATION_SUBSET>
optimization:
  use_gradient_accumulation: true
  enable_automatic_mixed_precision: false
  lr: 0.0001
  optimizer_type: AdamW
  kwargs:
    fused: true
    weight_decay: 0.01
  scheduler:
    schedulers:
      - type: LinearLR
        step_each_iteration: true
        kwargs:
          start_factor: 0.01
          end_factor: 1
          total_iters: 1414
      - type: ConstantLR
        step_each_iteration: true
    milestones: [1414]
stepper:
  ocean_fraction_prediction:
    land_fraction_name: land_fraction
    sea_ice_fraction_name_in_atmosphere: sea_ice_fraction
  sst_name: sst
  ocean:
    timedelta: 5D
    stepper:
      parameter_init:
        weights_path: /ocean_ckpt.tar
  atmosphere:
    timedelta: 6h
    loss_contributions:
      n_steps: 0
    stepper:
      parameter_init:
        weights_path: /atmos_ckpt.tar
        parameters:
          - frozen:
              include:
                - '*'
