atmosphere:
  zarr_path: /pscratch/sd/e/elynnwu/fme-dataset/2025-06-13-E3SMv3-coupled-piControl-atmosphere-data.zarr
  merge_zarr: /pscratch/sd/e/elynnwu/fme-dataset/2025-06-27-E3SMv3-coupled-piControl-atmosphere-sfc-wind-stress.zarr
  time_chunk_size: 500
  names:
    - TAUX
    - TAUY
    - surface_precipitation_rate
    - surface_upward_longwave_flux
    - surface_upward_shortwave_flux
    - FLDS
    - FSDS
    - LHFLX
    - SHFLX
ocean_timedelta: "5D"
output_name: E3SMv3-piControl-100yr-5daily-sfc-flux
output_directory: /pscratch/sd/e/elynnwu/fme-dataset
first_timestamp: "0401-01-03T12:00:00"
last_timestamp: "0501-12-29T12:00:00"
output_writer:
  n_dask_workers: 64
version: "2025-08-13"
