variable_sources:
  2025-10-15-cm4-piControl-200yr-ocean-no-smoothing.zarr:
    - deptho

dataset_computation:
  n_split: 50
  standard_names:
    longitude_dim: "lon"
    latitude_dim: "lat"
    time_dim: "time"
