# make cm4_1pctCO2_ocean_1daily_stats RESOLUTION=1deg
runs:
  2026-09-02-cm4-1pctCO2-1deg-ocean-1daily: ""  # store produced by scripts/gfdl_om4 xrbeam Dataflow pipeline
data_output_directory: gs://vcm-ml-intermediate
stats:
  output_directory: gs://vcm-ml-intermediate/2026-09-02-cm4-1pctCO2-1deg-ocean-1daily-stats
  data_type: CM4
  beaker_dataset: 2026-09-02-cm4-1pctCO2-1deg-ocean-1daily-stats
  start_date: "0001-01-02"
  end_date: "0141-01-01"
