# make cm4_1pctco2_ocean_stats RESOLUTION=4deg
runs:
  2026-07-15-om4-1pctco2-4deg-ocean-5daily: ""  # store produced by scripts/gfdl_om4 xrbeam Dataflow pipeline
data_output_directory: gs://vcm-ml-intermediate
stats:
  output_directory: gs://vcm-ml-intermediate/2026-07-15-om4-1pctco2-4deg-ocean-5daily-stats
  data_type: CM4
  beaker_dataset: 2026-07-15-om4-1pctco2-4deg-ocean-5daily-stats
  start_date: "0001-01-06"
  end_date: "0141-01-01"
