input_dataset:
  zarr_path: /climate-default/2025-03-21-CM4-piControl-atmosphere-land-1deg-8layer-200yr.zarr
  time_chunk_size: 500
  names:
    - surface_temperature
    - ocean_fraction
    - sea_ice_fraction
window_timedelta: "5D"
output_name: cm4-piControl-200yr-ts-6h-to-5Davg
output_directory: /climate-default
first_timestamp: "0151-01-06T00:00:00"
shift_timestamps_to_avg_interval_midpoint: true
output_writer:
  n_dask_workers: 64
version: "2025-08-22"
