input_dataset:
  zarr_path: /pscratch/sd/e/elynnwu/fme-dataset/2025-09-09-E3SMv3-coupled-piControl-atmosphere-100yr-preprocess-again.zarr
  time_chunk_size: 500
  names:
    - TS
    - ocean_fraction
    - sea_ice_fraction
window_timedelta: "5D"
output_name: e3smv3-piControl-100yr-ts-6h-to-5Davg
output_directory: /pscratch/sd/e/elynnwu/fme-dataset
first_timestamp: "0401-01-06T00:00:00"
shift_timestamps_to_avg_interval_midpoint: true
output_writer:
  n_dask_workers: 32
version: "2025-09-09"
