input_dataset:
  zarr_path: /pscratch/sd/e/elynnwu/fme-dataset/2025-09-09-E3SMv3-coupled-piControl-atmosphere-100yr-preprocess-again.zarr
  time_chunk_size: 500
  names:
    - surface_upward_longwave_flux
    - surface_upward_shortwave_flux
    - FLDS
    - FSDS
    - LHFLX
    - SHFLX
    - surface_precipitation_rate
    - TAUX
    - TAUY
window_timedelta: "5D"
output_name: e3smv3-piControl-100yr-5daily-sfc-flux
output_directory: /pscratch/sd/e/elynnwu/fme-dataset
first_timestamp: "0401-01-03T12:00:00"
last_timestamp: "0499-12-29T12:00:00"
output_writer:
  n_dask_workers: 32
version: "2025-09-09"
