runs:
  2024-07-11-era5-1deg-16layer-1940-2022: ""  # no real data source, config only for computing stats
data_output_directory: gs://vcm-ml-intermediate
stats:
  output_directory: gs://vcm-ml-intermediate/era5-1deg-16layer-stats-1990-2019
  beaker_dataset: era5-1deg-16layer-stats-1990-2019
  start_date: "1990-01-01"
  end_date: "2019-12-31"
  data_type: ERA5
