runs:
  2024-06-20-era5-1deg-8layer-1940-2022: ""  # no real data source, config only for computing stats
data_output_directory: gs://vcm-ml-intermediate
stats:
  output_directory: gs://vcm-ml-intermediate/2024-06-20-era5-1deg-8layer-stats-1990-2019
  beaker_dataset: era5-1deg-8layer-stats-1990-2019-v2
  start_date: "1990-01-01"
  end_date: "2019-12-31"
  data_type: ERA5
