runs:
  ic_0001: gs://vcm-ml-raw-flexible-retention/2023-07-08-C96-FME-reference-ensemble/regridded-zarrs/gaussian_grid_180_by_360/ic_0001
  ic_0002: gs://vcm-ml-raw-flexible-retention/2023-07-08-C96-FME-reference-ensemble/regridded-zarrs/gaussian_grid_180_by_360/ic_0002
  ic_0003: gs://vcm-ml-raw-flexible-retention/2023-07-08-C96-FME-reference-ensemble/regridded-zarrs/gaussian_grid_180_by_360/ic_0003
  ic_0004: gs://vcm-ml-raw-flexible-retention/2023-07-08-C96-FME-reference-ensemble/regridded-zarrs/gaussian_grid_180_by_360/ic_0004
  ic_0005: gs://vcm-ml-raw-flexible-retention/2023-07-08-C96-FME-reference-ensemble/regridded-zarrs/gaussian_grid_180_by_360/ic_0005
  ic_0006: gs://vcm-ml-raw-flexible-retention/2023-07-08-C96-FME-reference-ensemble/regridded-zarrs/gaussian_grid_180_by_360/ic_0006
  ic_0007: gs://vcm-ml-raw-flexible-retention/2023-07-08-C96-FME-reference-ensemble/regridded-zarrs/gaussian_grid_180_by_360/ic_0007
  ic_0008: gs://vcm-ml-raw-flexible-retention/2023-07-08-C96-FME-reference-ensemble/regridded-zarrs/gaussian_grid_180_by_360/ic_0008
  ic_0009: gs://vcm-ml-raw-flexible-retention/2023-07-08-C96-FME-reference-ensemble/regridded-zarrs/gaussian_grid_180_by_360/ic_0009
  ic_0010: gs://vcm-ml-raw-flexible-retention/2023-07-08-C96-FME-reference-ensemble/regridded-zarrs/gaussian_grid_180_by_360/ic_0010
  ic_0011: gs://vcm-ml-raw-flexible-retention/2023-07-08-C96-FME-reference-ensemble/regridded-zarrs/gaussian_grid_180_by_360/ic_0011
data_output_directory: gs://vcm-ml-intermediate/2023-08-09-vertically-resolved-1deg-fme-ensemble-dataset
stats:
  output_directory: gs://vcm-ml-intermediate/2023-08-09-vertically-resolved-1deg-fme-ensemble-dataset-stats
  beaker_dataset: 2023-08-09-vertically-resolved-1deg-fme-ensemble-dataset-stats
  start_date: "2021-01-01"
  end_date: "2030-12-31"
  data_type: FV3GFS
  exclude_runs:
    - "ic_0011"
dataset_computation:
  reference_vertical_coordinate_file: gs://vcm-ml-raw-flexible-retention/2023-04-13-11-year-C96-FME-reference/vertical-coordinate-file/fv_core.res.nc
  vertical_coarsening_indices:
    - [0, 18]
    - [18, 26]
    - [26, 31]
    - [31, 36]
    - [36, 41]
    - [41, 47]
    - [47, 53]
    - [53, 63]
  renaming:
    specific_humidity_at_two_meters: Q2m
  variable_sources:
    fluxes_2d.zarr:
      - PRATEsfc
      - LHTFLsfc
      - SHTFLsfc
      - DLWRFsfc
      - DSWRFsfc
      - DSWRFtoa
      - ULWRFsfc
      - ULWRFtoa
      - USWRFsfc
      - USWRFtoa
      - precipitable_water_path
      - GRAUPELsfc
      - ICEsfc
      - SNOWsfc
    fourcastnet_vanilla.zarr:
      - PRESsfc
      - HGTsfc
      - RH500
      - RH850
      - TMP500
      - TMP850
      - UGRD500
      - UGRD850
      - UGRD1000
      - VGRD500
      - VGRD850
      - VGRD1000
      - h50
      - h500
      - h850
      - h1000
      - TMP2m
      - UGRD10m
      - VGRD10m
    full_state.zarr:
      - surface_temperature
      - air_temperature
      - specific_humidity
      - cloud_water_mixing_ratio
      - cloud_ice_mixing_ratio
      - graupel_mixing_ratio
      - rain_mixing_ratio
      - snow_mixing_ratio
      - northward_wind
      - eastward_wind
      - pressure_thickness_of_atmospheric_layer
      - soil_moisture
      - specific_humidity_at_two_meters
    encoded_surface_type.zarr:
      - land_fraction
      - ocean_fraction
      - sea_ice_fraction
  standard_names:
    total_frozen_precip_rate: None
