runs:
  run_directory: /mntdata
stats:
  output_directory: /mntdata/2024-08-21-healpix-era5-dataset
  beaker_dataset: 2024-08-21-healpix-era5-dataset-stats
  start_date: "1990-01-01"
  end_date: "2019-12-31"
  data_type: ERA5
data_output_directory: /mntdata/2024-08-21-healpix-era5-dataset
dataset_computation:
  n_split: 400
  reference_vertical_coordinate_file: gs://vcm-ml-raw-flexible-retention/2023-04-13-11-year-C96-FME-reference/vertical-coordinate-file/fv_core.res.nc
  vertical_coarsening_indices:
    - [0, 18]
  standard_names:
    face_dim: "face"
  chunking:
    face_dim: -1
  variable_sources:
    2024-06-20-era5-1deg-8layer-1940-2022.zarr:
      - DLWRFsfc
      - DPT2m
      - DSWRFsfc
      - DSWRFtoa
      - HGTsfc
      - LHTFLsfc
      - PRATEsfc
      - PRESsfc
      - Q200
      - Q2m
      - Q500
      - Q850
      - SHTFLsfc
      - TMP200
      - TMP2m
      - TMP500
      - TMP850
      - UGRD10m
      - UGRD200
      - UGRD500
      - UGRD850
      - ULWRFsfc
      - ULWRFtoa
      - USWRFsfc
      - USWRFtoa
      - VGRD10m
      - VGRD200
      - VGRD500
      - VGRD850
      - air_temperature_0
      - air_temperature_1
      - air_temperature_2
      - air_temperature_3
      - air_temperature_4
      - air_temperature_5
      - air_temperature_6
      - air_temperature_7
      - ak_0
      - ak_1
      - ak_2
      - ak_3
      - ak_4
      - ak_5
      - ak_6
      - ak_7
      - ak_8
      - bk_0
      - bk_1
      - bk_2
      - bk_3
      - bk_4
      - bk_5
      - bk_6
      - bk_7
      - bk_8
      - eastward_wind_0
      - eastward_wind_1
      - eastward_wind_2
      - eastward_wind_3
      - eastward_wind_4
      - eastward_wind_5
      - eastward_wind_6
      - eastward_wind_7
      - h1000
      - h200
      - h250
      - h300
      - h500
      - h700
      - h850
      - land_fraction
      - latitude
      - longitude
      - northward_wind_0
      - northward_wind_1
      - northward_wind_2
      - northward_wind_3
      - northward_wind_4
      - northward_wind_5
      - northward_wind_6
      - northward_wind_7
      - ocean_fraction
      - sea_ice_fraction
      - soil_moisture_0
      - soil_moisture_1
      - soil_moisture_2
      - soil_moisture_3
      - specific_total_water_0
      - specific_total_water_1
      - specific_total_water_2
      - specific_total_water_3
      - specific_total_water_4
      - specific_total_water_5
      - specific_total_water_6
      - specific_total_water_7
      - surface_temperature
      - tendency_of_total_water_path_due_to_advection
      - time
      - total_column_water_vapour