runs:
  1xCO2-ic_0001: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/1xCO2-ic_0001
  1xCO2-ic_0002: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/1xCO2-ic_0002
  1xCO2-ic_0003: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/1xCO2-ic_0003
  1xCO2-ic_0004: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/1xCO2-ic_0004
  1xCO2-ic_0005: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/1xCO2-ic_0005
  2xCO2-ic_0001: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/2xCO2-ic_0001
  2xCO2-ic_0002: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/2xCO2-ic_0002
  2xCO2-ic_0003: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/2xCO2-ic_0003
  2xCO2-ic_0004: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/2xCO2-ic_0004
  2xCO2-ic_0005: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/2xCO2-ic_0005
  3xCO2-ic_0001: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/3xCO2-ic_0001
  3xCO2-ic_0002: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/3xCO2-ic_0002
  3xCO2-ic_0003: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/3xCO2-ic_0003
  3xCO2-ic_0004: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/3xCO2-ic_0004
  3xCO2-ic_0005: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/3xCO2-ic_0005
  4xCO2-ic_0001: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/4xCO2-ic_0001
  4xCO2-ic_0002: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/4xCO2-ic_0002
  4xCO2-ic_0003: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/4xCO2-ic_0003
  4xCO2-ic_0004: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/4xCO2-ic_0004
  4xCO2-ic_0005: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/4xCO2-ic_0005
  abrupt-2xCO2: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/abrupt-2xCO2
  abrupt-3xCO2: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/abrupt-3xCO2
  abrupt-4xCO2: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/abrupt-4xCO2
  increasing-CO2: gs://vcm-ml-raw-flexible-retention/2024-07-03-C24-SHiELD-SOM/regridded-zarrs/gaussian_grid_45_by_90/increasing-CO2
data_output_directory: gs://vcm-ml-intermediate/2024-07-17-vertically-resolved-4deg-c24-shield-som-baseline-fme-dataset
stats:
  output_directory: gs://vcm-ml-intermediate/2024-07-17-vertically-resolved-4deg-c24-shield-som-ensemble-fme-dataset-stats
  beaker_dataset: 2024-07-17-vertically-resolved-4deg-fme-c24-shield-som-ensemble-dataset-stats
  # These datasets already exclude the one-year divergence period for each
  # ensemble member, so we can use data from all times when computing the
  # stats.
  start_date: null
  end_date: null
  data_type: FV3GFS
  exclude_runs:
    # Exclude all runs here since we are not interested in these for ML training
    - 1xCO2-ic_0001
    - 1xCO2-ic_0002
    - 1xCO2-ic_0003
    - 1xCO2-ic_0004
    - 1xCO2-ic_0005
    - 2xCO2-ic_0001
    - 2xCO2-ic_0002
    - 2xCO2-ic_0003
    - 2xCO2-ic_0004
    - 2xCO2-ic_0005
    - 3xCO2-ic_0001
    - 3xCO2-ic_0002
    - 3xCO2-ic_0003
    - 3xCO2-ic_0004
    - 3xCO2-ic_0005
    - 4xCO2-ic_0001
    - 4xCO2-ic_0002
    - 4xCO2-ic_0003
    - 4xCO2-ic_0004
    - 4xCO2-ic_0005
    - abrupt-2xCO2
    - abrupt-3xCO2
    - abrupt-4xCO2
    - increasing-co2
dataset_computation:
  reference_vertical_coordinate_file: gs://vcm-ml-raw-flexible-retention/2024-03-10-C96-SHiELD-FME-reference/vertical-coordinate-file/fv_core.res.nc
  vertical_coarsening_indices:
    - [0, 11]
    - [11, 21]
    - [21, 30]
    - [30, 39]
    - [39, 49]
    - [49, 58]
    - [58, 67]
    - [67, 79]
  renaming:
    specific_humidity_at_two_meters: Q2m
    air_temperature_at_two_meters: TMP2m
    eastward_wind_at_ten_meters: UGRD10m
    northward_wind_at_ten_meters: VGRD10m
  variable_sources:
    fluxes_2d.zarr:
      - PRATEsfc
      - LHTFLsfc
      - SHTFLsfc
      - DLWRFsfc
      - DSWRFsfc
      - DSWRFtoa
      - ULWRFsfc
      - ULWRFtoa
      - USWRFsfc
      - USWRFtoa
      - precipitable_water_path
      - GRAUPELsfc
      - ICEsfc
      - SNOWsfc
    full_state.zarr:
      - surface_temperature
      - air_temperature
      - specific_humidity
      - cloud_water_mixing_ratio
      - cloud_ice_mixing_ratio
      - graupel_mixing_ratio
      - rain_mixing_ratio
      - snow_mixing_ratio
      - northward_wind
      - eastward_wind
      - pressure_thickness_of_atmospheric_layer
      - PRESsfc
      - HGTsfc
      - column_soil_moisture
      - soil_moisture_0
      - soil_moisture_1
      - soil_moisture_2
      - soil_moisture_3
      - land_fraction
      - ocean_fraction
      - sea_ice_fraction
      - specific_humidity_at_two_meters
      - air_temperature_at_two_meters
      - northward_wind_at_ten_meters
      - eastward_wind_at_ten_meters
      - RH200
      - RH500
      - RH850
      - TMP200
      - TMP500
      - TMP850
      - UGRD200
      - UGRD500
      - UGRD850
      - VGRD200
      - VGRD500
      - VGRD850
      - h50
      - h200
      - h500
      - h850
    ocean_forcing.zarr:
      - prescribed_mixed_layer_depth
      - prescribed_qflux
    scalar.zarr:
      - global_mean_co2
  standard_names:
    total_frozen_precip_rate: None
