experiment_dir: /scratch/cimes/wg4031/fme/valid/FloeNet-Samudra_coupling_finetune2_seed711/
n_coupled_steps: 3942
coupled_steps_in_memory: 18
checkpoint_path: /scratch/cimes/wg4031/fme/train/OM4_FloeNet-SamudraI_coupled2_seed711_4GPU/training_checkpoints/best_inference_ckpt.tar
data_writer:
  ocean:
    save_prediction_files: false
    save_monthly_files: true
  ice:
    save_prediction_files: false
    save_monthly_files: true
logging:
  log_to_screen: true
  log_to_wandb: false
  log_to_file: true
  project: ace-samudraI-om4
  entity: ai2cm
loader:
  num_data_workers: 1
  dataset:
    ocean:
      data_path: /scratch/cimes/wg4031/Emulator_data/Ocean/
      file_pattern: 1958-2022.OM41deg_Samudra_5daily_snapshots_NoLeap_shifttime.zarr
      engine: zarr
    ice:
      data_path: /scratch/cimes/wg4031/Emulator_data/Ice/
      file_pattern: 1958-2022.OM41deg_FloeNet_6hourly_NoLeap_trimvars.zarr
      engine: zarr
  start_indices:
    times:
      - '1968-12-29T12:00:00'