experiment_dir: /scratch/cimes/wg4031/fme/valid/OM4_FloeNet_6h_5docn_nexStep_seed711_1969-2022
n_forward_steps: 78839
forward_steps_in_memory: 40
checkpoint_path: /scratch/cimes/wg4031/fme/train/OM4_FloeNet_6h_5docn_nexStep_seed711_4GPU/training_checkpoints/best_inference_ckpt.tar
allow_incompatible_dataset: true
logging:
  log_to_screen: true
  log_to_wandb: false
  log_to_file: true
  project: ace-seaice-om4
  entity: ai2cm
loader:
  start_indices:
    times:
    - '1969-01-01T00:00:00'
  dataset:
    data_path: /scratch/cimes/wg4031/Emulator_data/Ice/
    file_pattern: 1958-2022.OM41deg_FloeNet_6hourly_NoLeap.zarr
    engine: zarr
  num_data_workers: 1
data_writer:
  save_prediction_files: false
  save_monthly_files: true
aggregator:
  log_histograms: true