seed: 0
experiment_dir: /results
save_checkpoint: true
checkpoint_every_n_batches: 5000
validate_using_ema: true
ema_checkpoint_save_epochs:
  start: 5
  step: 5
max_epochs: 80
ema:
  decay: 0.999
inference:
  - name: 10year
    weight: 0.0
    epochs:
      start: 1
      step: 2
    n_forward_steps: 3652
    forward_steps_in_memory: 40
    n_ensemble_per_ic: 1
    loader:
      start_indices:
        times:
          - '2015-01-01T06:00:00'
          - '2015-01-02T06:00:00'
          - '2015-01-03T06:00:00'
          - '2015-01-04T06:00:00'
          - '2015-01-05T06:00:00'
          - '2015-01-06T06:00:00'
          - '2015-01-07T06:00:00'
          - '2015-01-08T06:00:00'
      dataset:
        data_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-1940-2025.zarr
        file_pattern: 2026-03-19-era5-1deg-8layer-1940-2025.zarr
        engine: zarr
      num_data_workers: 8
    aggregator:
      step_means:
        - step: 5
          target: denorm
          name: day_5
          variables: &inference_variables
            - PRATEsfc
            - TMP2m
            - Q2m
            - UGRD10m
            - VGRD10m
            - h500
            - TMP850
            - PRESsfc
            - surface_temperature
            - ULWRFsfc
            - DLWRFsfc
            - USWRFsfc
            - DSWRFsfc
            - ULWRFtoa
            - USWRFtoa
            - LHTFLsfc
            - SHTFLsfc
            - tendency_of_total_water_path_due_to_advection
            - air_temperature_0
            - air_temperature_1
            - air_temperature_3
            - air_temperature_7
            - specific_total_water_0
            - specific_total_water_1
            - specific_total_water_3
            - specific_total_water_7
            - eastward_wind_0
            - eastward_wind_1
            - eastward_wind_3
            - eastward_wind_7
            - northward_wind_0
            - northward_wind_1
            - northward_wind_3
            - northward_wind_7
            - total_water_path
        - step: 5
          target: norm
          name: day_5_norm
          variables: *inference_variables
      ensembles: []
      mean_denorm:
        enabled: false
        target: denorm
      mean_norm:
        enabled: false
        target: norm
      enso_index:
        enabled: false
      enso_coefficient:
        enabled: false
      histogram:
        enabled: true
  - name: 10year_insample
    weight: 0.0
    epochs:
      start: 1
      step: 2
    n_forward_steps: 3652
    forward_steps_in_memory: 40
    n_ensemble_per_ic: 1
    loader:
      start_indices:
        times:
          - '1995-01-01T06:00:00'
          - '1995-01-02T06:00:00'
          - '1995-01-03T06:00:00'
          - '1995-01-04T06:00:00'
          - '1995-01-05T06:00:00'
          - '1995-01-06T06:00:00'
          - '1995-01-07T06:00:00'
          - '1995-01-08T06:00:00'
      dataset:
        data_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-1940-2025.zarr
        file_pattern: 2026-03-19-era5-1deg-8layer-1940-2025.zarr
        engine: zarr
      num_data_workers: 8
    aggregator:
      step_means:
        - step: 5
          target: denorm
          name: day_5
          variables: *inference_variables
        - step: 5
          target: norm
          name: day_5_norm
          variables: *inference_variables
      ensembles: []
      mean_denorm:
        enabled: false
        target: denorm
      mean_norm:
        enabled: false
        target: norm
      enso_index:
        enabled: false
      enso_coefficient:
        enabled: false
      histogram:
        enabled: true
  - name: weather_2024
    weight: 0.0
    n_forward_steps: 5
    forward_steps_in_memory: 5
    n_ensemble_per_ic: 8
    loader:
      start_indices:
        times:
          - '2024-06-01T06:00:00'
          - '2024-06-02T06:00:00'
          - '2024-06-03T06:00:00'
          - '2024-06-04T06:00:00'
          - '2024-06-05T06:00:00'
          - '2024-06-06T06:00:00'
          - '2024-06-07T06:00:00'
          - '2024-06-08T06:00:00'
      dataset:
        data_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-1940-2025.zarr
        file_pattern: 2026-03-19-era5-1deg-8layer-1940-2025.zarr
        engine: zarr
      num_data_workers: 8
    aggregator:
      step_means:
        - step: 5
          target: denorm
          name: day_5
          variables: *inference_variables
        - step: 5
          target: norm
          name: day_5_norm
          variables: *inference_variables
      ensembles:
        - step: 5
          name: day_5_ensemble
      mean_denorm:
        enabled: false
        target: denorm
      mean_norm:
        enabled: false
        target: norm
      power_spectrum:
        enabled: false
      zonal_mean:
        enabled: false
      time_mean_denorm:
        enabled: false
        target: denorm
      time_mean_norm:
        enabled: false
        target: norm
      annual:
        enabled: false
      enso_index:
        enabled: false
      enso_coefficient:
        enabled: false
      ipo_index:
        enabled: false
  - name: weather_1994
    weight: 0.0
    n_forward_steps: 5
    forward_steps_in_memory: 5
    n_ensemble_per_ic: 8
    loader:
      start_indices:
        times:
          - '1994-06-01T06:00:00'
          - '1994-06-02T06:00:00'
          - '1994-06-03T06:00:00'
          - '1994-06-04T06:00:00'
          - '1994-06-05T06:00:00'
          - '1994-06-06T06:00:00'
          - '1994-06-07T06:00:00'
          - '1994-06-08T06:00:00'
      dataset:
        data_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-1940-2025.zarr
        file_pattern: 2026-03-19-era5-1deg-8layer-1940-2025.zarr
        engine: zarr
      num_data_workers: 8
    aggregator:
      step_means:
        - step: 5
          target: denorm
          name: day_5
          variables: *inference_variables
        - step: 5
          target: norm
          name: day_5_norm
          variables: *inference_variables
      ensembles:
        - step: 5
          name: day_5_ensemble
      mean_denorm:
        enabled: false
        target: denorm
      mean_norm:
        enabled: false
        target: norm
      power_spectrum:
        enabled: false
      zonal_mean:
        enabled: false
      time_mean_denorm:
        enabled: false
        target: denorm
      time_mean_norm:
        enabled: false
        target: norm
      annual:
        enabled: false
      enso_index:
        enabled: false
      enso_coefficient:
        enabled: false
      ipo_index:
        enabled: false
  - name: ace2_5yr_1996
    weight: 1.0
    epochs:
      start: 1
      step: 2
    n_forward_steps: 1826
    forward_steps_in_memory: 40
    n_ensemble_per_ic: 1
    loader:
      start_indices:
        times:
          - '1996-01-01T06:00:00'
          - '1996-02-15T06:00:00'
          - '1996-04-01T06:00:00'
          - '1996-05-15T06:00:00'
          - '1996-07-01T06:00:00'
          - '1996-08-15T06:00:00'
          - '1996-10-01T06:00:00'
          - '1996-11-15T06:00:00'
      dataset:
        data_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-1940-2025.zarr
        file_pattern: 2026-03-19-era5-1deg-8layer-1940-2025.zarr
        engine: zarr
      num_data_workers: 8
    aggregator:
      step_means: []
      ensembles: []
      mean_denorm:
        enabled: false
        target: denorm
      mean_norm:
        enabled: false
        target: norm
      enso_index:
        enabled: false
      enso_coefficient:
        enabled: false
      histogram:
        enabled: true
logging:
  log_to_screen: true
  log_to_wandb: true
  log_to_file: true
  project: ace
  entity: ai2cm
train_loader:
  batch_size: 8
  num_data_workers: 8
  prefetch_factor: 4
  time_buffer: 1
  dataset:
    strict: false
    concat:
      - data_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-1940-2025.zarr
        file_pattern: 2026-03-19-era5-1deg-8layer-1940-2025.zarr
        engine: zarr
        subset:
          start_time: '1940-01-01'
          stop_time: '1943-12-31'
      - data_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-1940-2025.zarr
        file_pattern: 2026-03-19-era5-1deg-8layer-1940-2025.zarr
        engine: zarr
        subset:
          start_time: '1944-01-01'
          stop_time: '1948-12-31'
      - data_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-1940-2025.zarr
        file_pattern: 2026-03-19-era5-1deg-8layer-1940-2025.zarr
        engine: zarr
        subset:
          start_time: '1949-01-01'
          stop_time: '1953-12-31'
      - data_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-1940-2025.zarr
        file_pattern: 2026-03-19-era5-1deg-8layer-1940-2025.zarr
        engine: zarr
        subset:
          start_time: '1954-01-01'
          stop_time: '1958-12-31'
      - data_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-1940-2025.zarr
        file_pattern: 2026-03-19-era5-1deg-8layer-1940-2025.zarr
        engine: zarr
        subset:
          start_time: '1959-01-01'
          stop_time: '1963-12-31'
      - data_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-1940-2025.zarr
        file_pattern: 2026-03-19-era5-1deg-8layer-1940-2025.zarr
        engine: zarr
        subset:
          start_time: '1964-01-01'
          stop_time: '1968-12-31'
      - data_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-1940-2025.zarr
        file_pattern: 2026-03-19-era5-1deg-8layer-1940-2025.zarr
        engine: zarr
        subset:
          start_time: '1969-01-01'
          stop_time: '1973-12-31'
      - data_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-1940-2025.zarr
        file_pattern: 2026-03-19-era5-1deg-8layer-1940-2025.zarr
        engine: zarr
        subset:
          start_time: '1974-01-01'
          stop_time: '1978-12-31'
      - data_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-1940-2025.zarr
        file_pattern: 2026-03-19-era5-1deg-8layer-1940-2025.zarr
        engine: zarr
        subset:
          start_time: '1979-01-01'
          stop_time: '1986-03-31'
      - data_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-1940-2025.zarr
        file_pattern: 2026-03-19-era5-1deg-8layer-1940-2025.zarr
        engine: zarr
        subset:
          start_time: '1986-04-01'
          stop_time: '1993-07-31'
      - data_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-1940-2025.zarr
        file_pattern: 2026-03-19-era5-1deg-8layer-1940-2025.zarr
        engine: zarr
        subset:
          start_time: '1993-08-01'
          stop_time: '1995-12-31'
      - data_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-1940-2025.zarr
        file_pattern: 2026-03-19-era5-1deg-8layer-1940-2025.zarr
        engine: zarr
        subset:
          start_time: '2011-01-01'
          stop_time: '2014-12-31'
      - data_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-1940-2025.zarr
        file_pattern: 2026-03-19-era5-1deg-8layer-1940-2025.zarr
        engine: zarr
        subset:
          start_time: '2015-01-01'
          stop_time: '2019-12-31'
      - data_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-1940-2025.zarr
        file_pattern: 2026-03-19-era5-1deg-8layer-1940-2025.zarr
        engine: zarr
        subset:
          start_time: '2021-01-01'
          stop_time: '2022-12-31'
validation:
  loader:
    batch_size: 32
    num_data_workers: 8
    prefetch_factor: 2
    time_buffer: 3
    dataset:
      strict: false
      concat:
        - data_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-1940-2025.zarr
          file_pattern: 2026-03-19-era5-1deg-8layer-1940-2025.zarr
          engine: zarr
          subset:
            start_time: '1996-01-01'
            stop_time: '1997-12-31'
optimization:
  enable_automatic_mixed_precision: false
  lr: 0.0001
  optimizer_type: FusedAdam
  use_gradient_accumulation: true
  kwargs:
    weight_decay: 0.01
stepper_training:
  n_ensemble: 2
  n_forward_steps: 1
  optimize_last_step_only: true
  loss:
    type: EnsembleLoss
    kwargs:
      crps_weight: 0.9
      energy_score_weight: 0.1
    weights:
      h500: 5
stepper:
  step:
    type: single_module
    config:
      residual_prediction: true
      builder:
        type: NoiseConditionedSFNO
        config:
          embed_dim: 512
          noise_embed_dim: 32
          noise_type: isotropic
          filter_type: linear
          affine_norms: true
          normalize_big_skip: true
          filter_num_groups: 16
          spectral_ratio: 0.125
          use_mlp: true
          num_layers: 8
          operator_type: dhconv
      normalization:
        network:
          global_means_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-stats-1990-2019/2026-03-19-era5-1deg-8layer-1940-2025/centering.nc
          global_stds_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-stats-1990-2019/2026-03-19-era5-1deg-8layer-1940-2025/scaling-full-field.nc
        residual:
          global_means_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-stats-1990-2019/2026-03-19-era5-1deg-8layer-1940-2025/centering.nc
          global_stds_path: /climate-default/2026-03-19-era5-1deg-8layer-daily-stats-1990-2019/2026-03-19-era5-1deg-8layer-1940-2025/scaling-residual.nc
      ocean:
        surface_temperature_name: surface_temperature
        ocean_fraction_name: ocean_fraction
      corrector:
        conserve_dry_air: true
        moisture_budget_correction: advection_and_precipitation
        total_energy_budget_correction:
          method: constant_temperature
        force_positive_names:
        - specific_total_water_0
        - specific_total_water_1
        - specific_total_water_2
        - specific_total_water_3
        - specific_total_water_4
        - specific_total_water_5
        - specific_total_water_6
        - specific_total_water_7
        - Q2m
        - PRATEsfc
        - total_frozen_precipitation_rate
        - ULWRFsfc
        - ULWRFtoa
        - DLWRFsfc
        - DSWRFsfc
        - USWRFsfc
        - USWRFtoa
      next_step_forcing_names:
      - DSWRFtoa
      - global_mean_co2
      in_names:
      - land_fraction
      - ocean_fraction
      - sea_ice_fraction
      - DSWRFtoa
      - HGTsfc
      - global_mean_co2
      - PRESsfc
      - surface_temperature
      - air_temperature_0
      - air_temperature_1
      - air_temperature_2
      - air_temperature_3
      - air_temperature_4
      - air_temperature_5
      - air_temperature_6
      - air_temperature_7
      - specific_total_water_0
      - specific_total_water_1
      - specific_total_water_2
      - specific_total_water_3
      - specific_total_water_4
      - specific_total_water_5
      - specific_total_water_6
      - specific_total_water_7
      - eastward_wind_0
      - eastward_wind_1
      - eastward_wind_2
      - eastward_wind_3
      - eastward_wind_4
      - eastward_wind_5
      - eastward_wind_6
      - eastward_wind_7
      - northward_wind_0
      - northward_wind_1
      - northward_wind_2
      - northward_wind_3
      - northward_wind_4
      - northward_wind_5
      - northward_wind_6
      - northward_wind_7
      out_names:
      - PRESsfc
      - surface_temperature
      - air_temperature_0
      - air_temperature_1
      - air_temperature_2
      - air_temperature_3
      - air_temperature_4
      - air_temperature_5
      - air_temperature_6
      - air_temperature_7
      - specific_total_water_0
      - specific_total_water_1
      - specific_total_water_2
      - specific_total_water_3
      - specific_total_water_4
      - specific_total_water_5
      - specific_total_water_6
      - specific_total_water_7
      - eastward_wind_0
      - eastward_wind_1
      - eastward_wind_2
      - eastward_wind_3
      - eastward_wind_4
      - eastward_wind_5
      - eastward_wind_6
      - eastward_wind_7
      - northward_wind_0
      - northward_wind_1
      - northward_wind_2
      - northward_wind_3
      - northward_wind_4
      - northward_wind_5
      - northward_wind_6
      - northward_wind_7
      - TMP2m
      - Q2m
      - UGRD10m
      - VGRD10m
      - LHTFLsfc
      - SHTFLsfc
      - PRATEsfc
      - ULWRFsfc
      - ULWRFtoa
      - DLWRFsfc
      - DSWRFsfc
      - USWRFsfc
      - USWRFtoa
      - tendency_of_total_water_path_due_to_advection
      - TMP850
      - h500
      - total_frozen_precipitation_rate
      global_mean_removal:
        kind: shared
        append_as_input: true
