#!/usr/bin/env python
"""
Stitch per-snapshot downscaled cyclone events into a movie animating the
cyclone's track.

Reads the ``.nc`` outputs produced by ``fme.downscaling.predict`` for events
named ``<event_name>_<snapshot_date>`` (as generated by ``downscale_events.py``).
For each distinct ``<event_name>`` it groups the snapshots in time order and
renders an animation whose extent spans the union of all snapshot boxes. The
high-resolution downscaled patch is drawn at its own (moving) location on top of
upsampled coarse data that fills the rest of the frame.

Usage:
    python stitch_event_movie.py <events_dir> --coarse-data <ace_output.zarr> \\
        --variable PRMSL [--event-name tc_001] [--output-dir movies] \\
        [--reduction mean|sample] [--sample 0] [--fps 4] [--format gif]

The coarse data should be the same ACE global output zarr that was downscaled.
"""

import argparse
import re
from collections import defaultdict
from datetime import datetime
from pathlib import Path

import cftime
import matplotlib

matplotlib.use("Agg")
import cartopy.crs as ccrs  # noqa: E402
import imageio.v2 as imageio  # noqa: E402
import matplotlib.patches as mpatches  # noqa: E402
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import xarray as xr  # noqa: E402

# <event_name>_<YYYYMMDD[ThH]>.nc -> (event_name, datestamp)
_EVENT_FILE_RE = re.compile(r"(.+)_(\d{8}(?:T\d{2})?)\.nc$")

WIND_SPEED = "wind_speed"
U10_CANDIDATES = ("eastward_wind_at_ten_meters", "UGRD10m")
V10_CANDIDATES = ("northward_wind_at_ten_meters", "VGRD10m")


def _resolve_var(ds: xr.Dataset, candidates: tuple[str, ...], suffix: str = "") -> str:
    """Return the first ``candidates`` entry (plus ``suffix``) present in ``ds``."""
    for name in candidates:
        key = f"{name}{suffix}"
        if key in ds:
            return key
    raise KeyError(f"None of {candidates} (suffix={suffix!r}) found in dataset")


def parse_datestamp(stamp: str) -> datetime:
    """Parse a YYYYMMDD or YYYYMMDDThH datestamp."""
    if "T" in stamp:
        return datetime.strptime(stamp, "%Y%m%dT%H")
    return datetime.strptime(stamp, "%Y%m%d")


def group_event_files(directory: Path) -> dict[str, list[tuple[datetime, Path]]]:
    """Group .nc files by event name, each value sorted by snapshot time."""
    groups: dict[str, list[tuple[datetime, Path]]] = defaultdict(list)
    for path in sorted(directory.glob("*.nc")):
        match = _EVENT_FILE_RE.match(path.name)
        if match is None:
            continue
        groups[match.group(1)].append((parse_datestamp(match.group(2)), path))
    for event_name in groups:
        groups[event_name].sort(key=lambda item: item[0])
    return dict(groups)


def reduce_samples(da: xr.DataArray, reduction: str, sample: int) -> xr.DataArray:
    """Collapse the sample dimension of a predicted field."""
    if "sample" not in da.dims:
        return da
    if reduction == "mean":
        return da.mean("sample")
    return da.isel(sample=sample)


def load_patch(path: Path, variable: str, reduction: str, sample: int) -> xr.DataArray:
    """Load the high-resolution patch for ``variable`` from an event .nc file.

    ``wind_speed`` is derived from the eastward/northward 10m wind components.
    """
    ds = xr.open_dataset(path)
    if variable == WIND_SPEED:
        u_name = _resolve_var(ds, U10_CANDIDATES, "_predicted")
        v_name = _resolve_var(ds, V10_CANDIDATES, "_predicted")
        u = reduce_samples(ds[u_name], reduction, sample)
        v = reduce_samples(ds[v_name], reduction, sample)
        patch = np.hypot(u, v)
    else:
        patch = reduce_samples(ds[f"{variable}_predicted"], reduction, sample)
    return patch.load()


def normalize_coarse_lon(coarse: xr.Dataset, target_lons: np.ndarray) -> xr.Dataset:
    """Roll the coarse longitude coordinate into the patches' convention.

    The downscaled patch lon coordinate may be in either the [-180, 180] or
    [0, 360] convention; convert the coarse data to match so slicing lines up.
    """
    lon = coarse["lon"].values
    needs_negative = target_lons.min() < 0
    has_negative = lon.min() < 0
    if needs_negative and not has_negative:
        coarse = coarse.assign_coords(lon=((lon + 180.0) % 360.0) - 180.0)
    elif not needs_negative and has_negative:
        coarse = coarse.assign_coords(lon=lon % 360.0)
    return coarse.sortby("lon")


def select_coarse_var(coarse: xr.Dataset, variable: str) -> xr.DataArray:
    if variable == WIND_SPEED:
        u_name = _resolve_var(coarse, U10_CANDIDATES)
        v_name = _resolve_var(coarse, V10_CANDIDATES)
        return np.hypot(coarse[u_name], coarse[v_name])
    return coarse[variable]


def coarse_at_time(da: xr.DataArray, when: datetime) -> xr.DataArray:
    """Select the coarse snapshot nearest to ``when``, handling cftime."""
    times = da.indexes["time"]
    if len(times) and isinstance(times[0], cftime.datetime):
        target = type(times[0])(when.year, when.month, when.day, when.hour, when.minute)
    else:
        target = np.datetime64(when)
    return da.sel(time=target, method="nearest")


def crop(da: xr.DataArray, lat_bounds, lon_bounds, pad: float) -> xr.DataArray:
    """Crop a lat/lon field to bounds (with padding), order-agnostic."""
    lat_slice = slice(lat_bounds[0] - pad, lat_bounds[1] + pad)
    lon_slice = slice(lon_bounds[0] - pad, lon_bounds[1] + pad)
    if da["lat"].values[0] > da["lat"].values[-1]:
        lat_slice = slice(lat_bounds[1] + pad, lat_bounds[0] - pad)
    return da.sel(lat=lat_slice, lon=lon_slice)


def _edge_extent(da: xr.DataArray) -> tuple[float, float, float, float]:
    """Pixel-edge ``[lon0, lon1, lat0, lat1]`` extent for imshow.

    Coordinate values are cell centres, but ``imshow(extent=...)`` expects the
    outer edges of the corner pixels. Using centres shifts the image by half a
    grid cell, which is a visible ~0.5 deg offset for the coarse data and is the
    reason the high-res patch otherwise looks misaligned with the background.
    """

    def edges(coord: np.ndarray) -> tuple[float, float]:
        coord = np.sort(coord)
        d = (coord[-1] - coord[0]) / (len(coord) - 1) if len(coord) > 1 else 0.0
        return float(coord[0] - d / 2.0), float(coord[-1] + d / 2.0)

    lon0, lon1 = edges(da["lon"].values)
    lat0, lat1 = edges(da["lat"].values)
    return lon0, lon1, lat0, lat1


def oriented(da: xr.DataArray) -> tuple[np.ndarray, tuple[float, float, float, float]]:
    """Return ``(data, edge_extent)`` with rows/cols ordered for ``origin='lower'``.

    ACE output may store latitude descending; flip so the southernmost row is
    first, which is what ``origin='lower'`` assumes.
    """
    lat = da["lat"].values
    lon = da["lon"].values
    data = np.asarray(da.values, dtype=float)
    if lat[0] > lat[-1]:
        data = data[::-1, :]
    if lon[0] > lon[-1]:
        data = data[:, ::-1]
    return data, _edge_extent(da)


def compute_color_limits(
    patches: list[xr.DataArray],
    coarse_frames: list[xr.DataArray],
) -> tuple[float, float]:
    values = []
    for arr in (*patches, *coarse_frames):
        flat = np.asarray(arr.values, dtype=float).ravel()
        values.append(flat[np.isfinite(flat)])
    stacked = np.concatenate(values)
    return float(np.percentile(stacked, 2)), float(np.percentile(stacked, 98))


def render_event(
    event_name: str,
    snapshots: list[tuple[datetime, Path]],
    coarse_var: xr.DataArray,
    variable: str,
    reduction: str,
    sample: int,
    coarse_pad: float,
    cmap: str,
    fps: int,
    output_path: Path,
):
    patches = [load_patch(path, variable, reduction, sample) for _, path in snapshots]
    times = [when for when, _ in snapshots]

    # Full movie extent spans the union of all snapshot boxes.
    extents = [_edge_extent(p) for p in patches]
    lon_min = min(e[0] for e in extents)
    lon_max = max(e[1] for e in extents)
    lat_min = min(e[2] for e in extents)
    lat_max = max(e[3] for e in extents)

    coarse_var = normalize_coarse_lon(
        coarse_var.to_dataset(name="v"), np.array([lon_min, lon_max])
    )["v"]

    coarse_frames = [
        crop(
            coarse_at_time(coarse_var, when),
            (lat_min, lat_max),
            (lon_min, lon_max),
            coarse_pad,
        )
        for when in times
    ]

    vmin, vmax = compute_color_limits(patches, coarse_frames)

    track_lon = [0.5 * (e[0] + e[1]) for e in extents]
    track_lat = [0.5 * (e[2] + e[3]) for e in extents]

    frames = []
    for i, (when, patch) in enumerate(zip(times, patches)):
        fig = plt.figure(figsize=(6, 6))
        ax = plt.axes(projection=ccrs.PlateCarree())
        ax.set_extent([lon_min, lon_max, lat_min, lat_max], crs=ccrs.PlateCarree())

        coarse_data, coarse_extent = oriented(coarse_frames[i])
        ax.imshow(
            coarse_data,
            extent=coarse_extent,
            origin="lower",
            transform=ccrs.PlateCarree(),
            cmap=cmap,
            vmin=vmin,
            vmax=vmax,
            interpolation="bilinear",
            alpha=0.6,
            zorder=0,
        )

        patch_data, (p_lon0, p_lon1, p_lat0, p_lat1) = oriented(patch)
        img = ax.imshow(
            patch_data,
            extent=[p_lon0, p_lon1, p_lat0, p_lat1],
            origin="lower",
            transform=ccrs.PlateCarree(),
            cmap=cmap,
            vmin=vmin,
            vmax=vmax,
            zorder=2,
        )
        ax.add_patch(
            mpatches.Rectangle(
                (p_lon0, p_lat0),
                p_lon1 - p_lon0,
                p_lat1 - p_lat0,
                fill=False,
                edgecolor="white",
                linewidth=1.5,
                transform=ccrs.PlateCarree(),
                zorder=3,
            )
        )
        ax.plot(
            track_lon[: i + 1],
            track_lat[: i + 1],
            color="white",
            linewidth=1.0,
            marker="o",
            markersize=2,
            transform=ccrs.PlateCarree(),
            zorder=3,
        )
        ax.coastlines(color="black", linewidth=0.4)
        gl = ax.gridlines(
            draw_labels=True,
            linewidth=0.3,
            color="gray",
            alpha=0.5,
            linestyle="--",
        )
        gl.top_labels = False
        gl.right_labels = False
        gl.xlabel_style = {"size": 7}
        gl.ylabel_style = {"size": 7}
        ax.set_title(f"{event_name}  {when:%Y-%m-%d %H:%M}  ({variable})", fontsize=10)
        cbar = fig.colorbar(img, ax=ax, shrink=0.7)
        cbar.set_label(variable)

        fig.canvas.draw()
        buf = np.asarray(fig.canvas.buffer_rgba())
        frames.append(buf[..., :3].copy())
        plt.close(fig)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    imageio.mimsave(output_path, frames, fps=fps)
    print(f"Wrote {output_path} ({len(frames)} frames)")


def parse_args():
    parser = argparse.ArgumentParser(
        description="Stitch downscaled cyclone event snapshots into a track movie."
    )
    parser.add_argument(
        "events_dir", help="Directory containing predict.py event .nc outputs."
    )
    parser.add_argument(
        "--coarse-data",
        required=True,
        help="Path to the ACE global output zarr used for the background.",
    )
    parser.add_argument(
        "--variable",
        default="PRMSL",
        help="Variable to animate (e.g. PRMSL, PRATEsfc, wind_speed). "
        "wind_speed is derived from the 10m wind components.",
    )
    parser.add_argument(
        "--event-name",
        default=None,
        help="Only render this event name (default: render all detected events).",
    )
    parser.add_argument(
        "--output-dir", default="./event_movies", help="Output directory for movies."
    )
    parser.add_argument(
        "--reduction",
        choices=["mean", "sample"],
        default="mean",
        help="How to collapse the ensemble sample dimension (default: mean).",
    )
    parser.add_argument(
        "--sample",
        type=int,
        default=0,
        help="Sample index to show when --reduction=sample (default: 0).",
    )
    parser.add_argument(
        "--coarse-pad",
        type=float,
        default=1.0,
        help="Degrees of coarse data to include beyond the frame edges (default: 1).",
    )
    parser.add_argument("--cmap", default="turbo", help="Colormap (default: turbo).")
    parser.add_argument("--fps", type=int, default=4, help="Frames per second.")
    parser.add_argument(
        "--format", default="gif", help="Movie file extension, e.g. gif or mp4."
    )
    return parser.parse_args()


def main():
    args = parse_args()
    events_dir = Path(args.events_dir)
    groups = group_event_files(events_dir)
    if args.event_name is not None:
        groups = {k: v for k, v in groups.items() if k == args.event_name}
    if not groups:
        print(f"No matching event files found in {events_dir}")
        return

    coarse = xr.open_zarr(args.coarse_data)
    if "sample" in coarse.dims:
        coarse = coarse.isel(sample=0)
    coarse_var = select_coarse_var(coarse, args.variable)

    output_dir = Path(args.output_dir)
    for event_name, snapshots in groups.items():
        if len(snapshots) < 2:
            print(f"Skipping {event_name}: only {len(snapshots)} snapshot(s).")
            continue
        render_event(
            event_name=event_name,
            snapshots=snapshots,
            coarse_var=coarse_var,
            variable=args.variable,
            reduction=args.reduction,
            sample=args.sample,
            coarse_pad=args.coarse_pad,
            cmap=args.cmap,
            fps=args.fps,
            output_path=output_dir / f"{event_name}_{args.variable}.{args.format}",
        )


if __name__ == "__main__":
    main()
