seed: 0
experiment_dir: /results
save_checkpoint: true
checkpoint_every_n_batches: 5000
validate_using_ema: true
max_epochs: 60
ema:
  decay: 0.999
inference:
  - name: 10year
    weight: 1.0
    epochs:
      start: 0
      step: 2
    n_forward_steps: 3652
    forward_steps_in_memory: 73
    n_ensemble_per_ic: 1
    loader:
      start_indices:
        times:
          - '2015-01-01T00:00:00'
          - '2015-01-02T00:00:00'
          - '2015-01-03T00:00:00'
          - '2015-01-04T00:00:00'
          - '2015-01-05T00:00:00'
          - '2015-01-06T00:00:00'
          - '2015-01-07T00:00:00'
          - '2015-01-08T00:00:00'
      dataset:
        data_path: /climate-default
        file_pattern: 2026-04-17-era5-4deg-8layer-daily-1940-2025.zarr
        engine: zarr
      num_data_workers: 8
    aggregator:
      step_means:
        - step: 5
          target: denorm
          name: day_5
          variables: &inference_variables
            - PRATEsfc
            - TMP2m
            - Q2m
            - UGRD10m
            - VGRD10m
            - h500
            - TMP850
            - PRESsfc
            - surface_temperature
            - ULWRFsfc
            - DLWRFsfc
            - USWRFsfc
            - DSWRFsfc
            - ULWRFtoa
            - USWRFtoa
            - LHTFLsfc
            - SHTFLsfc
            - tendency_of_total_water_path_due_to_advection
            - air_temperature_0
            - air_temperature_1
            - air_temperature_3
            - air_temperature_7
            - specific_total_water_0
            - specific_total_water_1
            - specific_total_water_3
            - specific_total_water_7
            - eastward_wind_0
            - eastward_wind_1
            - eastward_wind_3
            - eastward_wind_7
            - northward_wind_0
            - northward_wind_1
            - northward_wind_3
            - northward_wind_7
        - step: 5
          target: norm
          name: day_5_norm
          variables: *inference_variables
      ensembles: []
      mean_denorm:
        enabled: false
        target: denorm
      mean_norm:
        enabled: false
        target: norm
      enso_index:
        enabled: false
      enso_coefficient:
        enabled: false
      histogram:
        enabled: true
  - name: weather_2024
    weight: 0.0
    n_forward_steps: 5
    forward_steps_in_memory: 5
    n_ensemble_per_ic: 8
    loader:
      start_indices:
        times:
          - '2024-06-01T00:00:00'
          - '2024-06-02T00:00:00'
          - '2024-06-03T00:00:00'
          - '2024-06-04T00:00:00'
          - '2024-06-05T00:00:00'
          - '2024-06-06T00:00:00'
          - '2024-06-07T00:00:00'
          - '2024-06-08T00:00:00'
      dataset:
        data_path: /climate-default
        file_pattern: 2026-04-17-era5-4deg-8layer-daily-1940-2025.zarr
        engine: zarr
      num_data_workers: 8
    aggregator:
      step_means:
        - step: 5
          target: denorm
          name: day_5
          variables: *inference_variables
        - step: 5
          target: norm
          name: day_5_norm
          variables: *inference_variables
      ensembles:
        - step: 5
          name: day_5_ensemble
      mean_denorm:
        enabled: false
        target: denorm
      mean_norm:
        enabled: false
        target: norm
      power_spectrum:
        enabled: false
      zonal_mean:
        enabled: false
      time_mean_denorm:
        enabled: false
        target: denorm
      time_mean_norm:
        enabled: false
        target: norm
      annual:
        enabled: false
      enso_index:
        enabled: false
      enso_coefficient:
        enabled: false
      ipo_index:
        enabled: false
  - name: weather_1994
    weight: 0.0
    n_forward_steps: 5
    forward_steps_in_memory: 5
    n_ensemble_per_ic: 8
    loader:
      start_indices:
        times:
          - '1994-06-01T00:00:00'
          - '1994-06-02T00:00:00'
          - '1994-06-03T00:00:00'
          - '1994-06-04T00:00:00'
          - '1994-06-05T00:00:00'
          - '1994-06-06T00:00:00'
          - '1994-06-07T00:00:00'
          - '1994-06-08T00:00:00'
      dataset:
        data_path: /climate-default
        file_pattern: 2026-04-17-era5-4deg-8layer-daily-1940-2025.zarr
        engine: zarr
      num_data_workers: 8
    aggregator:
      step_means:
        - step: 5
          target: denorm
          name: day_5
          variables: *inference_variables
        - step: 5
          target: norm
          name: day_5_norm
          variables: *inference_variables
      ensembles:
        - step: 5
          name: day_5_ensemble
      mean_denorm:
        enabled: false
        target: denorm
      mean_norm:
        enabled: false
        target: norm
      power_spectrum:
        enabled: false
      zonal_mean:
        enabled: false
      time_mean_denorm:
        enabled: false
        target: denorm
      time_mean_norm:
        enabled: false
        target: norm
      annual:
        enabled: false
      enso_index:
        enabled: false
      enso_coefficient:
        enabled: false
      ipo_index:
        enabled: false
  - name: long_46year
    weight: 0.0
    epochs:
      start: 0
      step: 5
    n_forward_steps: 16794
    forward_steps_in_memory: 73
    n_ensemble_per_ic: 1
    loader:
      start_indices:
        times:
          - '1979-01-01T00:00:00'
          - '1979-01-02T00:00:00'
          - '1979-01-03T00:00:00'
          - '1979-01-04T00:00:00'
          - '1979-01-05T00:00:00'
          - '1979-01-06T00:00:00'
          - '1979-01-07T00:00:00'
          - '1979-01-08T00:00:00'
      dataset:
        data_path: /climate-default
        file_pattern: 2026-04-17-era5-4deg-8layer-daily-1940-2025.zarr
        engine: zarr
      num_data_workers: 8
    aggregator:
      step_means: []
      ensembles: []
      mean_denorm:
        enabled: false
        target: denorm
      mean_norm:
        enabled: false
        target: norm
      zonal_mean:
        enabled: false
      time_mean_denorm:
        target: denorm
        variables: *inference_variables
      time_mean_norm:
        target: norm
        variables: *inference_variables
      annual:
        variables: *inference_variables
      power_spectrum:
        variables: *inference_variables
      histogram:
        enabled: true
logging:
  log_to_screen: true
  log_to_wandb: true
  log_to_file: true
  project: ace
  entity: ai2cm
train_loader:
  batch_size: 8
  num_data_workers: 4
  prefetch_factor: 4
  time_buffer: 8
  time_buffer_pool_size: 32
  dataset:
    strict: false
    concat:
      - data_path: /climate-default
        file_pattern: 2026-04-17-era5-4deg-8layer-daily-1940-2025.zarr
        engine: zarr
        subset:
          start_time: '1979-01-01'
          stop_time: '1993-12-31'
      - data_path: /climate-default
        file_pattern: 2026-04-17-era5-4deg-8layer-daily-1940-2025.zarr
        engine: zarr
        subset:
          start_time: '1995-01-01'
          stop_time: '2013-12-31'
validation:
  loader:
    batch_size: 32
    num_data_workers: 8
    prefetch_factor: 2
    time_buffer: 16
    dataset:
      strict: false
      concat:
        - data_path: /climate-default
          file_pattern: 2026-04-17-era5-4deg-8layer-daily-1940-2025.zarr
          engine: zarr
          subset:
            start_time: '1994-01-01'
            stop_time: '1994-12-31'
        - data_path: /climate-default
          file_pattern: 2026-04-17-era5-4deg-8layer-daily-1940-2025.zarr
          engine: zarr
          subset:
            start_time: '2014-01-01'
            stop_time: '2014-12-31'
optimization:
  enable_automatic_mixed_precision: false
  lr: 0.0001
  optimizer_type: FusedAdam
  use_gradient_accumulation: true
  kwargs:
    weight_decay: 0.01
stepper_training:
  n_ensemble: 2
  n_forward_steps: 1
  optimize_last_step_only: true
  loss:
    type: EnsembleLoss
    weights:
      air_temperature_0: 0.5
      air_temperature_1: 0.5
      eastward_wind_0: 0.5
      northward_wind_0: 0.5
      specific_total_water_0: 0.5
      specific_total_water_1: 0.25
      specific_total_water_2: 0.5
      PRATEsfc: 0.5
      h500: 10
      TMP850: 5
      Q2m: 0.5
      DLWRFsfc: 2
      ULWRFsfc: 5
      USWRFsfc: 2
      DSWRFsfc: 2
      USWRFtoa: 2
      tendency_of_total_water_path_due_to_advection: 0.5
      PRESsfc: 3
    kwargs:
      crps_weight: 0.9
      energy_score_weight: 0.1
stepper:
  step:
    type: single_module
    config:
      residual_prediction: false
      builder:
        type: NoiseConditionedSFNO
        config:
          embed_dim: 512
          noise_embed_dim: 32
          noise_type: isotropic
          filter_type: linear
          affine_norms: true
          normalize_big_skip: true
          filter_num_groups: 1
          use_mlp: true
          num_layers: 8
          operator_type: dhconv
          remove_latent_global_mean: true
          concat_latent_global_mean: every
      normalization:
        network:
          global_means_path: /climate-default/2026-04-17-era5-4deg-8layer-daily-stats-1990-2019/2026-03-19-era5-4deg-8layer-1940-2025/centering.nc
          global_stds_path: /climate-default/2026-04-17-era5-4deg-8layer-daily-stats-1990-2019/2026-03-19-era5-4deg-8layer-1940-2025/scaling-full-field.nc
        residual:
          global_means_path: /climate-default/2026-04-17-era5-4deg-8layer-daily-stats-1990-2019/2026-03-19-era5-4deg-8layer-1940-2025/centering.nc
          global_stds_path: /climate-default/2026-04-17-era5-4deg-8layer-daily-stats-1990-2019/2026-03-19-era5-4deg-8layer-1940-2025/scaling-residual.nc
      ocean:
        surface_temperature_name: surface_temperature
        ocean_fraction_name: ocean_fraction
      corrector:
        conserve_dry_air: true
        moisture_budget_correction: advection_and_precipitation
        force_positive_names:
        - specific_total_water_0
        - specific_total_water_1
        - specific_total_water_2
        - specific_total_water_3
        - specific_total_water_4
        - specific_total_water_5
        - specific_total_water_6
        - specific_total_water_7
        - Q2m
        - PRATEsfc
        - ULWRFsfc
        - ULWRFtoa
        - DLWRFsfc
        - DSWRFsfc
        - USWRFsfc
        - USWRFtoa
      next_step_forcing_names:
      - DSWRFtoa
      in_names:
      - land_fraction
      - ocean_fraction
      - sea_ice_fraction
      - DSWRFtoa
      - HGTsfc
      - PRESsfc
      - surface_temperature
      - TMP2m
      - Q2m
      - UGRD10m
      - VGRD10m
      - air_temperature_0
      - air_temperature_1
      - air_temperature_2
      - air_temperature_3
      - air_temperature_4
      - air_temperature_5
      - air_temperature_6
      - air_temperature_7
      - specific_total_water_0
      - specific_total_water_1
      - specific_total_water_2
      - specific_total_water_3
      - specific_total_water_4
      - specific_total_water_5
      - specific_total_water_6
      - specific_total_water_7
      - eastward_wind_0
      - eastward_wind_1
      - eastward_wind_2
      - eastward_wind_3
      - eastward_wind_4
      - eastward_wind_5
      - eastward_wind_6
      - eastward_wind_7
      - northward_wind_0
      - northward_wind_1
      - northward_wind_2
      - northward_wind_3
      - northward_wind_4
      - northward_wind_5
      - northward_wind_6
      - northward_wind_7
      out_names:
      - PRESsfc
      - surface_temperature
      - TMP2m
      - Q2m
      - UGRD10m
      - VGRD10m
      - air_temperature_0
      - air_temperature_1
      - air_temperature_2
      - air_temperature_3
      - air_temperature_4
      - air_temperature_5
      - air_temperature_6
      - air_temperature_7
      - specific_total_water_0
      - specific_total_water_1
      - specific_total_water_2
      - specific_total_water_3
      - specific_total_water_4
      - specific_total_water_5
      - specific_total_water_6
      - specific_total_water_7
      - eastward_wind_0
      - eastward_wind_1
      - eastward_wind_2
      - eastward_wind_3
      - eastward_wind_4
      - eastward_wind_5
      - eastward_wind_6
      - eastward_wind_7
      - northward_wind_0
      - northward_wind_1
      - northward_wind_2
      - northward_wind_3
      - northward_wind_4
      - northward_wind_5
      - northward_wind_6
      - northward_wind_7
      - LHTFLsfc
      - SHTFLsfc
      - PRATEsfc
      - ULWRFsfc
      - ULWRFtoa
      - DLWRFsfc
      - DSWRFsfc
      - USWRFsfc
      - USWRFtoa
      - tendency_of_total_water_path_due_to_advection
      - TMP850
      - h500
