inventory_path: gs://vcm-ml-intermediate/2026-04-28-cmip6-daily-pilot/inventory.csv
output_directory: gs://vcm-ml-intermediate/2026-04-28-cmip6-daily-pilot/v0

defaults:
  time_subset:
    historical: {start: "2010-01-01", end: "2010-12-31"}
    ssp585: {start: "2015-01-01", end: "2015-12-31"}

selection:
  exclude_source_ids:
    - INM-CM4-8
  experiments: [historical, ssp585]

overrides:
  - match:
      source_id: CESM2-WACCM
      experiment: historical
      variant_label: r2i1p1f1
    allow_dedupe: true
