"""
Parameterized regression tests for spatial parallelism.

Each ``RegressionCase`` defines a small nn.Module and input data.
The test:

1. Initializes global data and scatters it to local spatial chunks.
2. Runs a forward pass, reduces to a scalar, gathers the result.
3. Does a backward pass and SGD step.
4. Runs a second forward pass and reduction.
5. Compares all gathered outputs against a committed baseline.

Baselines must be generated by a single-rank ``python -m pytest`` run
and committed. Subsequent spatial-parallel runs validate correctness.
"""

import dataclasses
import pathlib
from abc import ABC, abstractmethod

import pytest
import torch

import fme
from fme.core.distributed.distributed import Distributed
from fme.core.testing.regression import validate_tensor_dict
from fme.core.typing_ import TensorDict

DATA_DIR = pathlib.Path(__file__).parent / "testdata"


class RegressionCase(ABC):
    """Base class for spatial-parallel regression test cases."""

    @abstractmethod
    def initialize(self) -> tuple[TensorDict, torch.nn.Module]:
        """Return global input data and an nn.Module.

        The module's forward method must accept a TensorDict and return
        a torch.Tensor.  Data tensors should have spatial dimensions as
        the last two dims.
        """
        ...

    @property
    @abstractmethod
    def img_shape(self) -> tuple[int, int]:
        """Global (lat, lon) shape. Must match the spatial dims of the data."""
        ...

    @property
    def lr(self) -> float:
        """Learning rate for the SGD step between forward passes."""
        return 0.01

    def reduce(self, tensor: torch.Tensor) -> torch.Tensor:
        """Reduce a spatially-distributed tensor to a global scalar.

        Default: local sum then spatial all-reduce.  Override to test
        other reduction paths (e.g. area-weighted mean).
        """
        local_sum = tensor.sum()
        return Distributed.get_instance().spatial_reduce_sum(local_sum)


# ---------------------------------------------------------------------------
# Concrete cases
# ---------------------------------------------------------------------------


class _Conv2dModule(torch.nn.Module):
    def __init__(self, conv: torch.nn.Conv2d):
        super().__init__()
        self.conv = conv

    def forward(self, data: TensorDict) -> torch.Tensor:
        return self.conv(data["x"])


@dataclasses.dataclass
class _LinearCase(RegressionCase):
    """1x1 Conv2d applied channel-wise; verifies basic gradient flow."""

    n_channels: int = 4
    img_shape: tuple[int, int] = (8, 16)

    def initialize(self) -> tuple[TensorDict, torch.nn.Module]:
        torch.manual_seed(0)
        data = {"x": torch.randn(2, self.n_channels, *self.img_shape)}
        conv = torch.nn.Conv2d(
            self.n_channels, self.n_channels, kernel_size=1, bias=True
        )
        return data, _Conv2dModule(conv)


# ---------------------------------------------------------------------------
# Test
# ---------------------------------------------------------------------------

CASES: dict[str, RegressionCase] = {
    "linear": _LinearCase(),
}


def _run_case(case: RegressionCase) -> TensorDict:
    """
    Execute the forward -> backward -> forward sequence, returning gathered outputs.
    """
    dist = Distributed.get_instance()
    device = fme.get_device()

    data, module = case.initialize()
    data = {k: v.to(device) for k, v in data.items()}
    module = module.to(device)
    module = dist.wrap_module(module)

    local_data = dist.scatter_spatial(data, case.img_shape)

    # First forward + reduce.
    out1 = module(local_data)
    scalar1 = case.reduce(out1)
    out1_global = dist.gather_spatial({"out": out1.detach()}, case.img_shape)

    # Backward + SGD step.
    optimizer = torch.optim.SGD(module.parameters(), lr=case.lr)
    optimizer.zero_grad()
    scalar1.backward()
    optimizer.step()

    # Second forward + reduce.
    out2 = module(local_data)
    scalar2 = case.reduce(out2)
    out2_global = dist.gather_spatial({"out": out2.detach()}, case.img_shape)

    return {
        "forward1/output": out1_global["out"],
        "forward1/scalar": scalar1.detach(),
        "forward2/output": out2_global["out"],
        "forward2/scalar": scalar2.detach(),
    }


@pytest.mark.parallel
@pytest.mark.parametrize("case_name", list(CASES.keys()))
def test_regression(case_name: str):
    dist = Distributed.get_instance()
    result = _run_case(CASES[case_name])
    if dist.is_root():
        validate_tensor_dict(
            result,
            DATA_DIR / f"regression_{case_name}.pt",
        )
