#!/bin/bash
#SBATCH -A devtech
#SBATCH --job-name devtech-e2prep:hindcast-$model-$year
#SBATCH -t 01:15:00
#SBATCH -o $model-$year.out
#SBATCH -e $model-$year.err
#SBATCH -p luna
#SBATCH -N 1



readonly DATA="/lustre/fsw/"

readonly _cont_image=gitlab-master.nvidia.com/earth-2/fcn-mip:23.03.22
readonly CODE="/home/$USER/"
readonly _cont_mounts="$DATA:$DATA:rw,$CODE:$CODE:rw"

srun \
-N 1 \
--ntasks-per-node=1 \
--container-image="$_cont_image" \
--container-name="era5_wind" \
--container-mounts="$_cont_mounts"\
--no-container-entrypoint \
--container-workdir=/root/fcn-mip bash -c '
pip install -e .
ldconfig
python3 workflows/hindcast/hindcast.py $year $model \
--root /lustre/fsw/sw_climate_fno/nbrenowitz/hindcast \
'
