#!/bin/bash

input_file="train-baseline.yaml"
search_string="1deg"
replacement_string="4deg"
output_file="train-baseline-4deg.yaml"

# Add an auto-generated warning comment to the output file
echo "# This file is auto-generated by update_4deg_config.sh. Do not edit directly." > "$output_file"
cat "$input_file" >> "$output_file"

# Use sed to perform the replacement (compatible with macOS and Linux)
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS version of sed requires an empty string after -i
    sed -i "" "s/${search_string}/${replacement_string}/g" "$output_file"
else
    sed -i "s/${search_string}/${replacement_string}/g" "$output_file"
fi

echo "Wrote 4-degree config to $output_file"
