
experiment_dir: /workdir/jeremym/monthly_data
data_loader:
  dataset:
    - data_path: /workdir/shared/2023-12-20-vertically-resolved-4deg-fme-amip-ensemble-dataset/train
  batch_size: 1
  num_data_workers: 1
logging:
  log_to_screen: true
  log_to_wandb: true
  log_to_file: true
  project: fourcastnet
  entity: ai2cm
forward_steps_in_memory: 73
variable_names:
  - DSWRFtoa
  - land_fraction
  - ocean_fraction
  - sea_ice_fraction
  - PRESsfc
  - surface_temperature
  - air_temperature_0
  - air_temperature_1
  - air_temperature_2
  - air_temperature_3
  - air_temperature_4
  - air_temperature_5
  - air_temperature_6
  - air_temperature_7
  - specific_total_water_0
  - specific_total_water_1
  - specific_total_water_2
  - specific_total_water_3
  - specific_total_water_4
  - specific_total_water_5
  - specific_total_water_6
  - specific_total_water_7
  - eastward_wind_0
  - eastward_wind_1
  - eastward_wind_2
  - eastward_wind_3
  - eastward_wind_4
  - eastward_wind_5
  - eastward_wind_6
  - eastward_wind_7
  - northward_wind_0
  - northward_wind_1
  - northward_wind_2
  - northward_wind_3
  - northward_wind_4
  - northward_wind_5
  - northward_wind_6
  - northward_wind_7
  - LHTFLsfc
  - SHTFLsfc
  - PRATEsfc
  - ULWRFsfc
  - ULWRFtoa
  - DLWRFsfc
  - DSWRFsfc
  - USWRFsfc
  - USWRFtoa
  - tendency_of_total_water_path_due_to_advection