experiment_dir: /scratch/cimes/wg4031/fme/train/OM4_FloeNet_6h_5docn_nexStep_seed711_4GPU
save_checkpoint: true
seed: 711
validate_using_ema: true
train_evaluation_samples: 0
ema:
  decay: 0.999
max_epochs: 50
inference:
  n_forward_steps: 3650
  forward_steps_in_memory: 40
  loader:
    start_indices:
      times:
      - '2006-01-01T00:00:00'
      - '2008-07-01T00:00:00'
      - '2011-01-01T00:00:00'
      - '2013-07-01T00:00:00'
    dataset:
      data_path: /scratch/cimes/wg4031/Emulator_data/Ice/
      file_pattern: 1958-2022.OM41deg_FloeNet_6hourly_Julian.zarr
      engine: zarr
    num_data_workers: 2
  aggregator:
    log_histograms: false
logging:
  log_to_screen: true
  log_to_wandb: true
  log_to_file: true
  project: ace-seaice-om4
  entity: ai2cm
  wandb_dir_in_experiment_dir: true
train_loader:
  batch_size: 32
  num_data_workers: 2
  prefetch_factor: 2
  time_buffer: 20
  dataset:
    data_path: /scratch/cimes/wg4031/Emulator_data/Ice/
    file_pattern: 1958-2022.OM41deg_FloeNet_6hourly_Julian.zarr
    engine: zarr
    subset:
      start_time: '1969-01-01'
      stop_time: '2005-12-31'
validation_loader:
  batch_size: 32
  num_data_workers: 2
  prefetch_factor: 2
  time_buffer: 20
  dataset:
    data_path: /scratch/cimes/wg4031/Emulator_data/Ice/
    file_pattern: 1958-2022.OM41deg_FloeNet_6hourly_Julian.zarr
    engine: zarr
    subset:
      start_time: '2016-01-01'
      stop_time: '2022-12-31'
train_aggregator:
  spherical_power_spectrum: false
  weighted_rmse: false
optimization:
  use_gradient_accumulation: true
  enable_automatic_mixed_precision: false
  lr: 0.0001
  optimizer_type: AdamW
  kwargs:
    weight_decay: 0.01
stepper_training:
  n_forward_steps: 8
  loss:
    type: MSE
    weights:
      siconc: 5
      simass: 10
      sisnmass: 5
      TS: 1
      SALTF: 1
      LSRCi: 1
      LSNKi: 1
      XPRTi: 1
      LSRCc: 1
      LSNKc: 1
      XPRTc: 1
      LSRCs: 1
      LSNKs: 1
      XPRTs: 1
      BMELT: 1
      TMELT: 1
stepper:
  input_masking:
    mask_value: 0
    fill_value: 0.0
    exclude_names_and_prefixes:
    - sea_surface_fraction
  step:
    type: single_module
    config:
      builder:
        type: FloeNet
        config:
          latent_dimension: 256
          activation: SiLU
          meshes: 6
          M0: 4
          bias: true
          radius_fraction: 1
          layernorm: true
          processor_steps: 4
          residual: true
          is_ocean: true
      normalization:
        network:
          global_means_path: /scratch/cimes/wg4031/Emulator_data/Ice/1969-2005.FloeNet_6hourly_means.nc
          global_stds_path: /scratch/cimes/wg4031/Emulator_data/Ice/1969-2005.FloeNet_6hourly_stds.nc
      corrector:
        type: ice_corrector
        config:
          budget_correction:
            corrected_variables:
              siconc:
              - LSRCc
              - LSNKc
              - XPRTc
              simass:
              - LSRCi
              - LSNKi
              - XPRTi
              sisnmass:
              - LSRCs
              - LSNKs
              - XPRTs
      next_step_forcing_names:
      - SWDN
      - LWDNjra
      - LH
      - SH
      - SNOWFL
      - wind_stress_x
      - wind_stress_y
      in_names:
      - siconc
      - simass
      - sisnmass
      - TS
      - SALTF
      - LSRCi
      - LSNKi
      - XPRTi
      - LSRCc
      - LSNKc
      - XPRTc
      - LSRCs
      - LSNKs
      - XPRTs
      - BMELT
      - TMELT
      - SWDN
      - LWDNjra
      - LH
      - SH
      - SNOWFL
      - wind_stress_x
      - wind_stress_y
      - tauuo
      - tauvo
      - tos
      - sos
      - zos
      out_names:
      - siconc
      - simass
      - sisnmass
      - TS
      - SALTF
      - LSRCi
      - LSNKi
      - XPRTi
      - LSRCc
      - LSNKc
      - XPRTc
      - LSRCs
      - LSNKs
      - XPRTs
      - BMELT
      - TMELT