apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: compute-fme-dataset-ensemble-
spec:
  entrypoint: compute-fme-dataset-ensemble
  volumes:
    - name: gcp-key-secret
      secret:
        defaultMode: 420
        secretName: gcp-key
  arguments:
    parameters:
    - name: python_script
    - name: ic_max
    - name: root
    - name: output
    - name: script_flags
      value: ""
  templates:
    - name: compute-fme-dataset-ensemble
      steps:
      - - name: compute-fme-dataset-individual
          template: compute-fme-dataset-individual
          arguments:
            parameters:
            - name: python_script
              value: "{{workflow.parameters.python_script}}"
            - name: ic
              value: "{{item}}"
            - name: root
              value: "{{workflow.parameters.root}}"
            - name: output
              value: "{{workflow.parameters.output}}"
            - name: script_flags
              value: "{{workflow.parameters.script_flags}}"
          withSequence:
            start: "1"
            end: "{{workflow.parameters.ic_max}}"
    - name: compute-fme-dataset-individual
      tolerations:
        - effect: NoSchedule
          key: dedicated
          value: med-sim-pool
      inputs:
        parameters:
          - name: python_script
          - name: ic
          - name: root
          - name: output
          - name: script_flags
      container:
        image: us.gcr.io/vcm-ml/fv3net:3d1589321e40cddc06bb88c22b44f597646473b2
        resources:
          limits:
            cpu: "8000m"
            memory: "27Gi"
          requests:
            cpu: "7500m"
            memory: "27Gi"
        command: ["bash", "-c", "-e"]
        args:
          - |
            cat << EOF > script.py
            {{inputs.parameters.python_script}}
            EOF

            python script.py --ic {{inputs.parameters.ic}} --root {{inputs.parameters.root}} \
              --output {{inputs.parameters.output}} {{inputs.parameters.script_flags}}
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /secret/gcp-credentials/key.json
          - name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
            value: /secret/gcp-credentials/key.json
        volumeMounts:
          - mountPath: /secret/gcp-credentials
            name: gcp-key-secret
