aggregator:
  mean_denorm:
    variables: null
    name: mean
    target: denorm
    enabled: true
  mean_norm:
    variables: null
    name: mean_norm
    target: norm
    enabled: true
  step_means:
  - step: 20
    variables: null
    name: mean_step_20
    target: denorm
    channel_mean_names: null
    enabled: true
  - step: 20
    variables: null
    name: mean_step_20_norm
    target: norm
    channel_mean_names: null
    enabled: true
  ensembles:
  - step: 20
    name: ensemble_step_20
    log_mean_maps: false
    enabled: true
  power_spectrum:
    variables: null
    name: power_spectrum
    enabled: true
  zonal_mean:
    variables: null
    name: zonal_mean
    zonal_mean_max_size: 4096
    enabled: true
  time_mean_denorm:
    variables: null
    name: time_mean
    target: denorm
    reference_data: null
    channel_mean_names: null
    enabled: true
  time_mean_norm:
    variables: null
    name: time_mean_norm
    target: norm
    reference_data: null
    channel_mean_names: null
    enabled: true
  video:
    variables: null
    name: video
    enable_extended_videos: false
    enabled: false
  histogram:
    variables: null
    name: histogram
    enabled: false
  seasonal:
    variables: null
    name: seasonal
    enabled: false
  annual:
    variables: null
    name: annual
    reference_data: null
    enabled: true
  enso_index:
    name: enso_index
    enabled: true
  enso_coefficient:
    name: enso_coefficient
    enabled: true
  monthly_reference_data: null
  time_mean_reference_data: null
