from functools import partial
from collections import OrderedDict
from copy import Error, deepcopy
from re import S
from numpy.lib.arraypad import pad
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.fft
from torch.nn.modules.container import Sequential
from torch.utils.checkpoint import checkpoint, checkpoint_sequential
from typing import Optional
import math

from torch_harmonics import *
from networks.geometric.contractions import *
from networks.geometric import activations

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.
    
    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)
        
    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)
        
        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)
        
        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()
        
        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)
                                                                                                                                
        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor
    
    
def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
    tensor: an n-dimensional `torch.Tensor`
    mean: the mean of the normal distribution
    std: the standard deviation of the normal distribution
    a: the minimum cutoff value
    b: the maximum cutoff value
    Examples:
    >>> w = torch.empty(3, 5)
    >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


@torch.jit.script
def drop_path(x: torch.Tensor, drop_prob: float = 0., training: bool = False) -> torch.Tensor:
    """Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).
    This is the same as the DropConnect impl I created for EfficientNet, etc networks, however,
    the original name is misleading as 'Drop Connect' is a different form of dropout in a separate paper...
    See discussion: https://github.com/tensorflow/tpu/issues/494#issuecomment-532968956 ... I've opted for
    changing the layer and argument names to 'drop path' rather than mix DropConnect as a layer name and use
    'survival rate' as the argument.
    """
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1. - drop_prob
    shape = (x.shape[0],) + (1,) * (x.ndim - 1)  # work with diff dim tensors, not just 2d ConvNets
    random_tensor = keep_prob + torch.rand(shape, dtype=x.dtype, device=x.device)
    random_tensor.floor_()  # binarize
    output = x.div(keep_prob) * random_tensor
    return output


class DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample  (when applied in main path of residual blocks).
    """
    def __init__(self, drop_prob=None):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob
        
    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training) 


class PatchEmbed(nn.Module):
    def __init__(self, img_size=(224, 224), patch_size=(16, 16), in_chans=3, embed_dim=768):
        super(PatchEmbed, self).__init__()
        num_patches = (img_size[1] // patch_size[1]) * (img_size[0] // patch_size[0])
        self.img_size = img_size
        self.patch_size = patch_size
        self.num_patches = num_patches
        self.proj = nn.Conv2d(in_chans, embed_dim, kernel_size=patch_size, stride=patch_size)
        
    def forward(self, x):
        # gather input
        B, C, H, W = x.shape
        assert H == self.img_size[0] and W == self.img_size[1], f"Input image size ({H}*{W}) doesn't match model ({self.img_size[0]}*{self.img_size[1]})."
        # new: B, C, H*W
        x = self.proj(x).flatten(2)
        return x

    
class MLP(nn.Module):
    def __init__(self, in_features, hidden_features = None, out_features = None, act_layer = nn.GELU, drop_rate = 0., checkpointing = False):
        super(MLP, self).__init__()
        self.checkpointing = checkpointing
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Conv2d(in_features, hidden_features, 1, bias=True)
        self.act = act_layer()
        self.fc2 = nn.Conv2d(hidden_features, out_features, 1, bias=True)
        self.drop = nn.Dropout(drop_rate) if drop_rate > 0. else nn.Identity()
        self.fwd = nn.Sequential(self.fc1, self.act, self.drop, self.fc2, self.drop)

    @torch.jit.ignore
    def checkpoint_forward(self, x):
        return checkpoint(self.fwd, x)
        
    def forward(self, x):
        if self.checkpointing:
            return self.checkpoint_forward(x)
        else:
            return self.fwd(x)


class SpectralConv2d(nn.Module):
    """
    Spectral Convolution as utilized in 
    """
    
    def __init__(self,
                 input_dims,
                 output_dims,
                 hidden_size,
                 sparsity_threshold = 0.0,
                 hard_thresholding_fraction = 1,
                 use_complex_kernels = False,
                 compression = None,
                 bias = False):
        super(SpectralConv2d, self).__init__()
        
        self.hidden_size = hidden_size
        self.sparsity_threshold = sparsity_threshold
        self.hard_thresholding_fraction = hard_thresholding_fraction
        self.scale = 0.02
        self.contract_handle = compl_contract2d_fwd_c if use_complex_kernels else compl_contract2d_fwd

        self.output_dims = output_dims
        modes_H = min(output_dims[0], input_dims[0]) // 2 + 1
        modes_W = min(output_dims[1], input_dims[1]) // 2 + 1
        self.modes_H = int(modes_H * self.hard_thresholding_fraction)
        self.modes_W = int(modes_W * self.hard_thresholding_fraction)

        # new simple linear layer
        self.wl = nn.Parameter(self.scale * torch.randn(self.hidden_size, self.hidden_size, self.modes_H, self.modes_W, 2))
        self.wh = nn.Parameter(self.scale * torch.randn(self.hidden_size, self.hidden_size, self.modes_H, self.modes_W, 2))
        # optional bias
        if bias:
            self.b = nn.Parameter(self.scale * torch.randn(1, self.hidden_size, *self.output_dims))

        
    def forward(self, x):
        
        dtype = x.dtype
        x = x.float()
        B, C, H, W = x.shape
        
        x = torch.fft.rfft2(x, dim=(-2, -1), norm="ortho")
        
        # do spectral conv
        x = torch.view_as_real(x)
        modes = torch.zeros(x.shape, device=x.device)

        modes[:, :, :self.modes_H,  :self.modes_W, :] = self.contract_handle(x[:, :, :self.modes_H,  :self.modes_W, :], self.wh)
        modes[:, :, -self.modes_H:, :self.modes_W, :] = self.contract_handle(x[:, :, -self.modes_H:, :self.modes_W, :], self.wl)
        
        # finalize
        x = F.softshrink(modes, lambd=self.sparsity_threshold)
        x = torch.view_as_complex(x)
        x = torch.fft.irfft2(x, s=self.output_dims, dim=(-2,-1), norm="ortho")
        if hasattr(self, 'b'):
            x = x + self.b
        x = x.type(dtype)
    
        return x

class SpectralConvS2(nn.Module):
    """
    Spectral Convolution as utilized in 
    """
    
    def __init__(self,
                 input_dims,
                 output_dims,
                 hidden_size,
                 sparsity_threshold=0.0,
                 hard_thresholding_fraction=1,
                 use_complex_kernels=False,
                 compression = None,
                 rank = 128,
                 input_grid = 'legendre-gauss',
                 output_grid = 'legendre-gauss',
                 bias = False):
        super(SpectralConvS2, self).__init__()
        
        self.hidden_size = hidden_size
        self.sparsity_threshold = sparsity_threshold
        self.hard_thresholding_fraction = hard_thresholding_fraction
        self.scale = 0.02

        self.input_dims = input_dims
        self.output_dims = output_dims

        # compute the modes to keep
        modes_lat = min(output_dims[0], input_dims[0])
        modes_lon = min(output_dims[1], input_dims[1]) // 2 + 1
        self.modes_lat = int(modes_lat * self.hard_thresholding_fraction)
        self.modes_lon = int(modes_lon * self.hard_thresholding_fraction)

        self.forward_transform = RealSHT(*input_dims, lmax=self.modes_lat, mmax=self.modes_lon, grid=input_grid).float()
        self.inverse_transform = InverseRealSHT(*output_dims, lmax=self.modes_lat, mmax=self.modes_lon, grid=output_grid).float()

        # remember the lower triangular indices
        ii, jj = torch.tril_indices(self.modes_lat, self.modes_lon)
        self.register_buffer("ii", ii)
        self.register_buffer("jj", jj)

        if compression == 'tt':
            self.rank = rank
            # tensortrain coefficients
            g1 = nn.Parameter(self.scale * torch.randn(self.hidden_size, self.rank, 2))
            g2 = nn.Parameter(self.scale * torch.randn(self.rank, self.hidden_size, self.rank, 2))
            g3 = nn.Parameter(self.scale * torch.randn(self.rank, len(ii), 2))
            self.w = nn.ParameterList([g1, g2, g3])

            self.contract_handle = contract_tt #if use_complex_kernels else raise(NotImplementedError)
        else:
            self.w = nn.Parameter(self.scale * torch.randn(self.hidden_size, self.hidden_size, len(ii), 2))
            self.contract_handle = compl_contract_fwd_c if use_complex_kernels else compl_contract_fwd

    
        if bias:
            self.b = nn.Parameter(self.scale * torch.randn(1, self.hidden_size, *self.output_dims))

        
    def forward(self, x):

        dtype = x.dtype
        x = x.float()
        B, C, H, W = x.shape
        
        x = self.forward_transform(x)
        
        # do spectral conv
        x = torch.view_as_real(x)
        modes = torch.zeros(x.shape, device=x.device)
        modes[:, :, self.ii, self.jj, :] = self.contract_handle(x[:, :, self.ii, self.jj, :], self.w)

        # finalize
        x = F.softshrink(modes, lambd=self.sparsity_threshold)
        x = torch.view_as_complex(x)

        x = torch.tril(x) # probably can skip the tril
        x = self.inverse_transform(x)
        if hasattr(self, 'b'):
            x = x + self.b
        x = x.type(dtype)
    
        return x

class SpectralAttention2d(nn.Module):
    """
    Spectral Attention layer according to AFNO paper
    """
    
    def __init__(self,
                 hidden_size,
                 num_blocks=8,
                 sparsity_threshold=0.0,
                 hard_thresholding_fraction=1,
                 hidden_size_factor=1,
                 use_complex_kernels=False):
        super(SpectralAttention2d, self).__init__()
        assert hidden_size % num_blocks == 0, f"hidden_size {hidden_size} should be divisble by num_blocks {num_blocks}"
        
        self.hidden_size = hidden_size
        self.sparsity_threshold = sparsity_threshold
        self.num_blocks = num_blocks
        self.block_size = self.hidden_size // self.num_blocks
        self.hard_thresholding_fraction = hard_thresholding_fraction
        self.hidden_size_factor = hidden_size_factor
        self.scale = 0.02
        self.mul_add_handle = compl_mul_add_fwd_c if use_complex_kernels else compl_mul_add_fwd
        self.mul_handle = compl_mul_fwd_c if use_complex_kernels else compl_mul_fwd
        
        # new
        self.w1 = nn.Parameter(self.scale * torch.randn(self.num_blocks, self.block_size, self.block_size * self.hidden_size_factor, 2))
        # self.b1 = nn.Parameter(self.scale * torch.randn(self.num_blocks, self.block_size * self.hidden_size_factor, 1, 1, 2))
        self.w2 = nn.Parameter(self.scale * torch.randn(self.num_blocks, self.block_size * self.hidden_size_factor, self.block_size, 2))
        # self.b2 = nn.Parameter(self.scale * torch.randn(self.num_blocks, self.block_size, 1, 1, 2))

        self.b = nn.Parameter(self.scale * torch.randn(1, self.num_blocks*self.block_size, 1, 1))
        
    def forward(self, x):
        
        bias = x
        
        dtype = x.dtype
        x = x.float()
        B, C, H, W = x.shape
        total_modes_H = H // 2 + 1
        total_modes_W = W // 2 + 1
        kept_modes_H = int(total_modes_H * self.hard_thresholding_fraction)
        kept_modes_W = int(total_modes_W * self.hard_thresholding_fraction)
        
        x = torch.fft.rfft2(x, dim=(-2, -1), norm="ortho")
        x = x.view(B, self.num_blocks, self.block_size, H, W // 2 + 1)
        
        # do spectral conv
        x = torch.view_as_real(x)
        modes = torch.zeros(x.shape, device=x.device)

        ol = F.relu(self.mul_handle(x[:, :, :, :kept_modes_H,  :kept_modes_W, :], self.w1))
        oh = F.relu(self.mul_handle(x[:, :, :, -kept_modes_H:, :kept_modes_W, :], self.w1))
    
        # modes[:, :, :, :kept_modes_H,  :kept_modes_W, :] = self.mul_add_handle(ol, self.w2, self.b2)
        # modes[:, :, :, -kept_modes_H:, :kept_modes_W, :] = self.mul_add_handle(oh, self.w2, self.b2)
        modes[:, :, :, :kept_modes_H,  :kept_modes_W, :] = self.mul_handle(ol, self.w2)
        modes[:, :, :, -kept_modes_H:, :kept_modes_W, :] = self.mul_handle(oh, self.w2)
        
        # finalize
        x = F.softshrink(modes, lambd=self.sparsity_threshold)
        x = torch.view_as_complex(x)
        x = x.reshape(B, C, H, W // 2 + 1)
        x = torch.fft.irfft2(x, s=(H, W), dim=(-2,-1), norm="ortho")
        x = x.type(dtype)
    
        return x + bias + self.b

class SpectralAttentionS2(nn.Module):
    """
    geometrical Spectral Attention layer
    """
    
    def __init__(self,
                 input_dims,
                 output_dims,
                 hidden_size,
                 num_blocks = 8,
                 sparsity_threshold = 0.0,
                 hard_thresholding_fraction = 1,
                 hidden_size_factor = 1,
                 use_complex_kernels = False,
                 complex_activation = 'real',
                 input_grid = 'legendre-gauss',
                 output_grid = 'legendre-gauss',
                 bias = False):
        super(SpectralAttentionS2, self).__init__()
        assert hidden_size % num_blocks == 0, f"hidden_size {hidden_size} should be divisble by num_blocks {num_blocks}"
        
        self.hidden_size = hidden_size
        self.sparsity_threshold = sparsity_threshold
        self.num_blocks = num_blocks
        self.block_size = self.hidden_size // self.num_blocks
        self.hard_thresholding_fraction = hard_thresholding_fraction
        self.hidden_size_factor = hidden_size_factor
        self.scale = 0.02
        # self.mul_add_handle = self.compl_mul_add_fwd_c if use_complex_kernels else self.compl_mul_add_fwd
        self.mul_handle = compl_mul_fwd_c if use_complex_kernels else compl_mul_fwd

        self.input_dims = input_dims
        self.output_dims = output_dims

        # compute the modes to keep
        modes_lat = min(output_dims[0], input_dims[0])
        modes_lon = min(output_dims[1], input_dims[1]) // 2 + 1
        self.modes_lat = int(modes_lat * self.hard_thresholding_fraction)
        self.modes_lon = int(modes_lon * self.hard_thresholding_fraction)

        self.forward_transform = RealSHT(*input_dims, lmax=self.modes_lat, mmax=self.modes_lon, grid=input_grid).float()
        self.inverse_transform = InverseRealSHT(*output_dims, lmax=self.modes_lat, mmax=self.modes_lon, grid=output_grid).float()

        # remember the lower triangular indices
        ii, jj = torch.tril_indices(self.modes_lat, self.modes_lon)
        self.register_buffer("ii", ii)
        self.register_buffer("jj", jj)

        # new
        self.w1 = nn.Parameter(self.scale * torch.randn(self.num_blocks, self.block_size, self.block_size * self.hidden_size_factor, 2))
        self.w2 = nn.Parameter(self.scale * torch.randn(self.num_blocks, self.block_size * self.hidden_size_factor, self.block_size, 2))

        if bias:
            self.b = nn.Parameter(self.scale * torch.randn(1, self.num_blocks*self.block_size, 1, 1))

        if complex_activation == 'modulus':
            self.activation = activations.mod_relu
        elif complex_activation == 'real':
            self.activation = activations.real_relu
        else:
            self.activation = activations.cart_relu

    def forward(self, x):

        dtype = x.dtype
        x = x.float()
        B, C, H, W = x.shape

        x = self.forward_transform(x)
        x = x.view(B, self.num_blocks, self.block_size, self.modes_lat, self.modes_lon)
        
        # do spectral conv
        x = torch.view_as_real(x)
        modes = torch.zeros(x.shape, device=x.device)
        
        o = self.mul_handle(x[:, :, :, self.ii, self.jj, :], self.w1)
        o = self.activation(o)
        modes[:, :, :, self.ii, self.jj, :] = self.mul_handle(o, self.w2)
        
        # finalize
        x = F.softshrink(modes, lambd=self.sparsity_threshold)
        x = torch.view_as_complex(x)

        x = x.reshape(B, C, self.modes_lat, self.modes_lon)

        x = self.inverse_transform(x)
        x = x.type(dtype)
        if hasattr(self, 'b'):
            x = x + self.b

        return x
